export const BLESS = [
  { id: 'wind', t: 0, k: '風', n: 'Tailwind', d: 'Enemies strike 12% slower.' },
  { id: 'eye', t: 0, k: '眼', n: 'Keen eye', d: 'Perfect arc 30% larger.' },
  { id: 'ward', t: 0, k: '守', n: 'Ward', d: 'One mistake per wave is forgiven.' },
  { id: 'focus', t: 0, k: '集', n: 'Focus', d: 'Parry window 25% longer.' },
  { id: 'fortune', t: 0, k: '福', n: 'Fortune', d: 'Score ×1.25.' },
  { id: 'edge', t: 0, k: '鋭', n: 'Keen edge', d: 'Duel openings need one fewer swipe.' },
  { id: 'calm', t: 0, k: '静', n: 'Calm', d: 'Half as many feints.' },
  { id: 'momentum', t: 0, k: '勢', n: 'Momentum', d: 'Combo multiplier climbs every 3 cuts.' },
  { id: 'breath', t: 0, lives: 1, k: '息', n: 'Second wind', d: 'Regain a life after each duel.' },
  {
    id: 'zanshin',
    t: 0,
    k: '残心',
    n: 'Zanshin',
    d: 'Your first mistake each stage keeps your combo.',
  },
  {
    id: 'foresight',
    t: 0,
    k: '先',
    n: 'Foresight',
    d: 'The next attacker always shows his arrow, even at night, in fog or blade only.',
  },
  {
    id: 'fox',
    t: 0,
    k: '狐',
    n: 'Fox sight',
    d: 'Feinting enemies show their true direction faintly.',
  },
  { id: 'stormborn', t: 0, k: '嵐', n: 'Stormborn', d: 'Weather hazards halved.' },
  {
    id: 'knifedance',
    t: 0,
    k: '舞',
    n: 'Knife Dance',
    d: 'Every third consecutive perfect cut restores one throwing knife.',
  },
  {
    id: 'stolentempo',
    t: 0,
    k: '間',
    n: 'Stolen Tempo',
    d: 'Your first perfect cut each wave makes the next attacker hesitate.',
  },
  {
    id: 'finalflourish',
    t: 0,
    k: '結',
    n: 'Final Flourish',
    d: 'Perfectly cut the last foe to gain a ward for the next wave.',
  },
  {
    id: 'swallow',
    t: 1,
    k: '燕',
    n: 'Swallow cut',
    d: 'A perfect cut also kills the next enemy if his blade points the same way.',
  },
  {
    id: 'still',
    t: 1,
    k: '静心',
    n: 'Still mind',
    d: 'Time slows for a moment when the ring reaches the perfect arc.',
  },
  {
    id: 'flurry',
    t: 1,
    k: '連斬',
    n: 'Flurry',
    d: 'Every 10th cut in a combo is automatically perfect.',
  },
  {
    id: 'counter',
    t: 1,
    k: '返し',
    n: 'Counter',
    d: 'Every parry in a duel also wounds the boss.',
  },
  { id: 'iron', t: 0, lives: 1, k: '鉄', n: 'Iron will', d: 'One more life, and heal one now.' },
  { id: 'patience', t: 0, k: '忍', n: 'Patience', d: '20% more time between attackers.' },
  { id: 'whetstone', t: 0, k: '研', n: 'Whetstone', d: 'Normal cuts score 40% more.' },
  { id: 'duelist', t: 0, k: '決', n: 'Duelist', d: 'Duel score ×1.5.' },
  { id: 'steady', t: 0, k: '定', n: 'Steady hand', d: 'Duel openings 20% longer.' },
  { id: 'lantern', t: 0, k: '灯', n: 'Lantern', d: 'Arrows never fade at night.' },
  { id: 'harvest', t: 0, k: '穫', n: 'Harvest', d: 'Wave-clear bonus ×2.5.' },
  { id: 'quickstep', t: 0, k: '速', n: 'Quick step', d: 'Swipes register at 75% of the distance.' },
  {
    id: 'paperward',
    t: 0,
    lives: 1,
    k: '符',
    n: 'Paper wards',
    d: 'Your next two mistakes are forgiven.',
  },
  {
    id: 'phoenix',
    t: 1,
    k: '鳳',
    n: 'Phoenix',
    d: 'Once, when you fall, rise again with full lives.',
  },
  { id: 'echo', t: 1, k: '響', n: 'Echo', d: 'Every perfect cut adds 2 extra to your combo.' },
  {
    id: 'tempest',
    t: 1,
    k: '颯',
    n: 'Tempest',
    d: 'Every 5th kill cuts down a second enemy for free.',
  },
  {
    id: 'timestop',
    t: 1,
    k: '刻',
    n: 'Hourglass',
    d: 'Time slows for every duel opening after a parry.',
  },
  { id: 'gold', t: 1, k: '黄金', n: 'Golden touch', d: 'Score ×1.5.' },
  {
    id: 'stormcall',
    t: 1,
    k: '雷',
    n: 'Stormcall',
    d: 'Three consecutive perfect cuts charge lightning that kills the next attacker.',
  },
  {
    id: 'rekindle',
    t: 1,
    k: '再',
    n: 'Rekindle',
    d: 'Once per wave, your first perfect cut after a broken combo restores half the lost combo.',
  },
  {
    id: 'crossroads',
    t: 1,
    k: '岐',
    n: 'Crossroads',
    d: 'Gain a curse immediately. Future Shrines offer two extra choices.',
  },
  {
    id: 'twin',
    t: 1,
    k: '双',
    n: 'Twin blessing',
    d: 'Receive two random common blessings at once.',
  },
  { id: 'dragon', t: 1, k: '龍', n: "Dragon's eye", d: 'Perfect arc 50% larger.' },
  { id: 'mercy', t: 1, k: '慈', n: 'Mercy', d: 'Feinting enemies show their true direction.' },
  {
    id: 'banner',
    t: 1,
    k: '旗',
    n: 'War banner',
    d: 'Once your combo passes 10, mistakes only drop it back to 10.',
  },
  {
    id: 'glass',
    t: 2,
    lives: 1,
    k: '硝子',
    n: 'Glass cannon',
    d: 'Drop to a single life for good. Score ×2.5.',
  },
  {
    id: 'frenzy',
    t: 2,
    k: '狂',
    n: 'Frenzy',
    d: 'Attackers come almost back to back, 15% faster. Combo multiplier caps at ×6.',
  },
  {
    id: 'silence',
    t: 2,
    k: '無音',
    n: 'Silence',
    d: 'Attack rings vanish, so time every cut by eye. Score ×1.7.',
  },
  { id: 'blood', t: 2, lives: 1, k: '血', n: 'Blood price', d: 'Lose a life now. All score ×2.' },
  {
    id: 'oath',
    t: 2,
    k: '誓',
    n: 'Oath of Precision',
    d: 'Normal cuts do not build combo. Five consecutive perfect cuts grant a ward.',
  },
  {
    id: 'haste',
    t: 2,
    k: '急',
    n: 'Haste',
    d: 'Enemies strike 20% faster. Perfect cuts score triple.',
  },
  {
    id: 'blind',
    t: 2,
    k: '目隠',
    n: 'Blindfold',
    d: 'Arrows vanish for the rest of the run. Score ×1.8.',
  },
];
export const TIER = ['', 'rare', 'cursed'],
  TIERNAME = ['', 'Rare', 'Cursed'];
/**
 * A Shrine reward held for the current run in RunState.bless (a set of IDs).
 * `t` is offer tier: 0 common, 1 rare, 2 cursed; `k`, `n` and `d` are the glyph,
 * name and effect description. Truthy `lives` marks life-related offers excluded
 * from Zen and hard mode; it is NOT an amount of healing.
 *
 * To add one, extend BLESS and implement its effect: shrine/blessings.ts owns
 * offer eligibility and immediate effects, equipment/modifiers.ts owns composed
 * numeric effects, and runtime/combat consumers handle triggered effects by ID.
 * A description alone does not apply an effect. Offers omit already-owned IDs.
 */
export type Blessing = (typeof BLESS)[number];
export const BLESS_BY: Record<string, Blessing> = Object.fromEntries(
  BLESS.map((blessing) => [blessing.id, blessing]),
);
