import type { Statistics } from '../progression/statistics.ts';
import { deathsTotal } from '../progression/statistics.ts';
import type { Modifiers } from '../equipment/modifiers.ts';
import { trialRewardItems } from './trials.ts';
export type ItemCategory = 'blade' | 'robe' | 'charm' | 'crest' | 'pet' | 'fx' | 'film' | 'seal';
/**
 * An Armoury catalog entry, including both gameplay equipment and cosmetics.
 * Ownership is stored separately as a set of stable IDs; equipped IDs are stored
 * per ItemCategory in platform/saves.ts. progression/unlocks.ts evaluates `ok`.
 * Blade, robe and charm modifier sources are composed by the runtime; visual
 * categories are consumed by rendering/UI. Adding catalog metadata alone does
 * not implement a new effect: wire its modifier or visual consumer as well.
 */
export interface Item {
  /** Stable saved identity, also used to join blade visuals and awakenings. */
  id: string;
  type: ItemCategory;
  /** Japanese glyph/label shown on the item card. */
  k: string;
  /** Display name. */
  n: string;
  /** Flavour text. */
  f: string;
  /** Optional non-mechanical role shown for a neutral starter loadout. */
  role?: string;
  /** Perk and tradeoff descriptions; mechanics are supplied through `m`. */
  pk?: string;
  tr?: string;
  /** Visible unlock requirement, or a cryptic hint for a hidden item. */
  d?: string;
  hint?: string;
  /** Truthy for a secret item whose locked card conceals its identity. */
  hidden?: number;
  /** Equipment effects; see computeModifiers for stacking rules. */
  m?: Partial<Modifiers>;
  /** Eligibility predicate, not an ownership check. May depend on earlier
   * catalog unlocks through createItems' getUnlocks callback.
   */
  ok: (stats: Statistics) => boolean;
}
export function createItems(getUnlocks: () => ReadonlySet<string>): Item[] {
  return [
    ...trialRewardItems(),
    {
      id: 'steel',
      type: 'blade',
      k: '玉鋼',
      n: 'Tamahagane',
      f: 'A dependable edge for an unhurried hand.',
      role: 'Balanced · no modifiers',
      ok: () => true,
      m: {},
    },
    {
      id: 'kuro',
      type: 'blade',
      k: '黒鉄',
      n: 'Kurogane',
      f: 'Black iron, bright edge.',
      pk: 'Parry window 15% longer',
      tr: 'Perfect arc 20% smaller',
      d: 'Win your first duel.',
      ok: (s) => s.duels >= 1,
      m: { parry: 1.15, pz: 0.04 },
    },
    {
      id: 'beni',
      type: 'blade',
      k: '紅',
      n: 'Beni',
      f: 'A red line down the edge.',
      pk: 'Perfect cut score ×1.5',
      tr: 'Normal cut score ×0.8',
      d: 'Land 25 perfect cuts.',
      ok: (s) => s.perfects >= 25,
      m: { perfect: 1.5, normal: 0.8 },
    },
    {
      id: 'tsuki',
      type: 'blade',
      k: '月影',
      n: 'Tsukikage',
      f: 'Its long edge catches the moonlight.',
      pk: 'Perfect arc 25% larger',
      tr: 'Enemies strike 6% faster',
      d: 'Reach the moonlit night.',
      ok: (s) => s.furthestStage >= 8,
      m: { pz: -0.05, atk: 0.94 },
    },
    {
      id: 'oboro',
      type: 'blade',
      k: '朧',
      n: 'Oboro',
      f: 'Half steel, half mist.',
      pk: 'Score ×1.2',
      tr: 'Feints 10 percentage points more likely',
      d: 'Reach wave 6 in Ronin mode.',
      ok: (s) => s.roninWave >= 6,
      m: { score: 1.2, feint: 0.1 },
    },
    {
      id: 'mura',
      type: 'blade',
      k: '村正',
      n: 'Muramasa',
      f: 'Cursed. It wants blood.',
      pk: 'Score ×1.4',
      tr: 'Enemies strike 12% faster',
      d: 'Score 50,000 in one run.',
      ok: (s) => s.bestScore >= 50000,
      m: { score: 1.4, atk: 0.88 },
    },
    {
      id: 'raijin',
      type: 'blade',
      k: '雷神',
      n: 'Raijin',
      f: 'It hums before a storm.',
      pk: 'Duel openings 20% longer',
      tr: 'Parry window 10% shorter',
      d: 'Win 10 duels.',
      ok: (s) => s.duels >= 10,
      m: { stag: 1.2, parry: 0.9 },
    },
    {
      id: 'sakura',
      type: 'blade',
      k: '桜',
      n: 'Sakura',
      f: 'Petals follow the edge.',
      pk: 'Combo multiplier climbs every 4 cuts',
      tr: 'Duel score ×0.5',
      d: 'Reach the cherry blossoms.',
      ok: (s) => s.furthestStage >= 2,
      m: { comboStep: 4, bossScore: 0.5 },
    },
    {
      id: 'kage',
      type: 'blade',
      k: '影',
      n: 'Kage',
      f: 'It leaves an afterimage.',
      pk: 'One wrong swipe per duel opening is ignored',
      tr: 'No perfect arc shown',
      d: 'Land 10 perfect cuts in a row.',
      ok: (s) => s.bestPStreak >= 10,
      m: { kage: 1, noArc: 1 },
    },
    {
      id: 'bokken',
      type: 'blade',
      k: '木刀',
      n: 'Bokken',
      f: 'A training sword. Humbling.',
      pk: 'Enemies strike 15% slower',
      tr: 'Score ×0.5',
      d: 'Fall on wave 1 ten times.',
      ok: (s) => s.w1deaths >= 10,
      m: { atk: 1.15, score: 0.5 },
    },
    {
      id: 'kodachi',
      type: 'blade',
      k: '小太刀',
      n: 'Kodachi',
      f: 'A short blade that turns in close quarters.',
      pk: 'Swipes register at 50% distance',
      tr: 'Parry window 15% shorter',
      d: 'Land 50 perfect cuts.',
      ok: (s) => s.perfects >= 50,
      m: { swipe: 0.5, parry: 0.85 },
    },
    {
      id: 'doji',
      type: 'blade',
      k: '童子切',
      n: 'Dōjigiri',
      f: 'It cut down a demon king.',
      pk: 'Every boss hit counts double',
      tr: 'No shrine blessings',
      d: 'Win 15 duels.',
      ok: (s) => s.duels >= 15,
      m: { bossDmg: 2, noShrine: 1 },
    },
    {
      id: 'kiku',
      type: 'blade',
      k: '菊一文字',
      n: 'Kiku-ichimonji',
      f: 'A chrysanthemum guards the hilt.',
      pk: 'First mistake each wave keeps your combo',
      tr: 'Score ×0.85',
      d: 'Reach a 60 combo.',
      ok: (s) => s.bestCombo >= 60,
      m: { kiku: 1, score: 0.85 },
    },
    {
      id: 'yuki',
      type: 'blade',
      k: '雪',
      n: 'Yuki',
      f: 'Cold enough to still the air.',
      pk: 'Perfect cuts freeze the next attacker briefly',
      tr: 'Normal cut score ×0.75',
      d: 'Accept 10 shrine blessings.',
      ok: (s) => s.shrines >= 10,
      m: { freeze: 1, normal: 0.75 },
    },
    {
      id: 'masamune',
      type: 'blade',
      k: '正宗',
      n: 'Masamune',
      f: "The calm master's blade.",
      pk: 'Restore 1 life every 15 clean cuts',
      tr: 'Score ×0.85',
      d: 'Reach wave 12 without losing a life.',
      ok: (s) => s.flawlessWave >= 12,
      m: { restore: 15, score: 0.85 },
    },
    {
      id: 'orochi',
      type: 'blade',
      k: '大蛇',
      n: 'Orochi',
      f: 'A serpent sleeps in the steel.',
      pk: '25% chance a cut also takes the next enemy whose blade points the same way',
      tr: 'Enemies strike 8% faster',
      d: 'Cut down 1,000 foes.',
      ok: (s) => s.kills >= 1000,
      m: { serpent: 0.25, atk: 0.92 },
    },
    {
      id: 'onikiri',
      type: 'blade',
      k: '鬼切',
      n: 'Onikiri',
      f: 'It has tasted demon blood.',
      pk: 'Duel openings need one fewer swipe',
      tr: 'Parry window 15% shorter',
      d: 'Win 20 duels.',
      ok: (s) => s.duels >= 20,
      m: { chain: -1, parry: 0.85 },
    },
    {
      id: 'tsubame',
      type: 'blade',
      k: '燕返',
      n: 'Tsubame-gaeshi',
      f: "Named for the swallow's turn.",
      pk: 'Perfect arc 20% larger; perfect cut score ×1.25',
      tr: 'Enemies strike 10% faster',
      d: 'Land 20 perfect cuts in a row.',
      ok: (s) => s.bestPStreak >= 20,
      m: { pz: -0.04, perfect: 1.25, atk: 0.9 },
    },
    {
      id: 'koken',
      type: 'blade',
      hidden: 1,
      k: '光剣',
      n: 'Kōken',
      f: 'A blade of pure light. It hums.',
      pk: 'Perfect arc 25% larger',
      tr: 'Score ×0.9',
      hint: 'Old codes still work on the title screen.',
      ok: (s) => s.konami >= 1,
      m: { pz: -0.05, score: 0.9 },
    },
    {
      id: 'pan',
      type: 'blade',
      hidden: 1,
      k: '鍋',
      n: 'Frying pan',
      f: 'It was the nearest thing to hand.',
      pk: 'Parry window 40% longer, and foes are knocked out cold',
      tr: 'Score ×0.5; no perfect cuts',
      hint: 'Those who flinch reach for the nearest thing.',
      ok: (s) => ((s.deaths || {}).early || 0) >= 5,
      m: { parry: 1.4, score: 0.5, noPerfect: 1, noArc: 1, bonk: 1 },
    },
    {
      id: 'sumi',
      type: 'robe',
      k: '墨',
      n: 'Sumi',
      f: 'Ink-dark cloth worn soft by the road.',
      role: 'Balanced · no modifiers',
      ok: () => true,
      m: {},
    },
    {
      id: 'hai',
      type: 'robe',
      k: '灰',
      n: 'Ash',
      f: 'The grey of a burnt field.',
      pk: 'Enemies strike 5% slower',
      tr: 'Parry window 10% shorter',
      d: 'Cut down 100 foes.',
      ok: (s) => s.kills >= 100,
      m: { atk: 1.05, parry: 0.9 },
    },
    {
      id: 'aka',
      type: 'robe',
      k: '赤',
      n: 'Akabane',
      f: 'A red sash keeps its colour through dust and rain.',
      pk: 'Combo multiplier caps at ×5',
      tr: 'Enemies strike 5% faster',
      d: 'Reach a 40 combo.',
      ok: (s) => s.bestCombo >= 40,
      m: { comboCap: 5, atk: 0.95 },
    },
    {
      id: 'kasa',
      type: 'robe',
      k: '笠',
      n: 'Wanderer',
      f: 'A straw kasa hides the eyes.',
      pk: 'Feints 10 percentage points less likely',
      tr: 'Bosses have 1 more health',
      d: 'Win 5 duels.',
      ok: (s) => s.duels >= 5,
      m: { feint: -0.1, bossHp: 1 },
    },
    {
      id: 'shiro',
      type: 'robe',
      k: '白',
      n: 'Shiro',
      f: 'White, like a death robe.',
      pk: 'Score ×1.3',
      tr: 'Enemies strike 8% faster',
      d: 'Score 20,000 in one run.',
      ok: (s) => s.bestScore >= 20000,
      m: { score: 1.3, atk: 0.92 },
    },
    {
      id: 'oni',
      type: 'robe',
      k: '鬼面',
      n: 'Oni mask',
      f: 'A demon face tied at the side.',
      pk: 'Parry window 20% longer',
      tr: 'Duel openings 15% shorter',
      d: 'Win a duel without a failed opening.',
      ok: (s) => s.cleanDuels >= 1,
      m: { parry: 1.2, stag: 0.85 },
    },
    {
      id: 'tengu',
      type: 'robe',
      k: '天狗',
      n: 'Tengu mask',
      f: 'Long nose, longer sight.',
      pk: 'Perfect arc 20% larger',
      tr: 'Score ×0.9',
      d: 'Land 100 perfect cuts.',
      ok: (s) => s.perfects >= 100,
      m: { pz: -0.04, score: 0.9 },
    },
    {
      id: 'monk',
      type: 'robe',
      k: '僧',
      n: 'Monk hood',
      f: 'Welcome at every shrine.',
      pk: '+1 Shrine choice',
      tr: 'Score ×0.9',
      d: 'Accept 5 shrine blessings.',
      ok: (s) => s.shrines >= 5,
      m: { shrineN: 4, score: 0.9 },
    },
    {
      id: 'mino',
      type: 'robe',
      k: '蓑',
      n: 'Straw cape',
      f: 'Rain runs off it.',
      pk: 'Weather hazards 50% weaker',
      tr: 'Enemies strike 5% faster',
      d: 'Reach the stormy shore.',
      ok: (s) => s.furthestStage >= 7,
      m: { hazard: 0.5, atk: 0.95 },
    },
    {
      id: 'helm',
      type: 'robe',
      k: '兜',
      n: 'Kabuto',
      f: 'Iron over the skull.',
      pk: 'First life-losing hit per run is warded',
      tr: 'Score ×0.85',
      d: 'Reach wave 20.',
      ok: (s) => s.bestWave >= 20,
      m: { runWard: 1, score: 0.85 },
    },
    {
      id: 'jinbaori',
      type: 'robe',
      k: '陣羽織',
      n: 'Jinbaori',
      f: "A commander's war coat.",
      pk: '+2 starting lives',
      tr: 'Score ×0.8',
      d: 'Reach wave 12.',
      ok: (s) => s.bestWave >= 12,
      m: { lives: 2, score: 0.8 },
    },
    {
      id: 'shinobi',
      type: 'robe',
      k: '忍',
      n: 'Shinobi',
      f: 'Nobody sees you coming.',
      pk: 'Standoffs twice as common; standoff score ×2',
      tr: 'One fewer starting life',
      d: 'Win 5 standoffs.',
      ok: (s) => s.standoffs >= 5,
      m: { standoff: 2, lives: -1 },
    },
    {
      id: 'kitsune',
      type: 'robe',
      k: '狐面',
      n: 'Kitsune mask',
      f: 'A fox sees through tricks.',
      pk: 'Feints show their true direction',
      tr: 'Enemies strike 8% faster',
      d: 'Defeat Kyōgetsu the Mirror.',
      ok: (s) => s.mirrorWins >= 1,
      m: { foxsight: 1, atk: 0.92 },
    },
    {
      id: 'noh',
      type: 'robe',
      k: '能面',
      n: 'Noh mask',
      f: 'Calm, whatever happens.',
      pk: '1 guaranteed rare blessing per Shrine when available',
      tr: 'Score ×0.9',
      d: 'Take 3 rare blessings.',
      ok: (s) => s.rares >= 3,
      m: { rareShrine: 1, score: 0.9 },
    },
    {
      id: 'yoroi',
      type: 'robe',
      k: '鎧',
      n: 'Yoroi',
      f: 'Lacquered plates settle with a low rattle.',
      pk: '+10% Embers earned',
      tr: 'Enemies strike 10% faster; score ×0.85',
      d: 'Reach wave 24.',
      ok: (s) => s.bestWave >= 24,
      m: { emberBonus: 0.1, atk: 0.9, score: 0.85 },
    },
    {
      id: 'komuso',
      type: 'robe',
      k: '虚無僧',
      n: 'Komusō',
      f: 'A wandering monk behind a basket.',
      pk: 'Score ×1.3 when arrows are hidden',
      tr: 'Parry window 10% shorter',
      d: 'Reach wave 9 in blade-only mode.',
      ok: (s) => s.bladeWave >= 9,
      m: { bladeScore: 1.3, parry: 0.9 },
    },
    {
      id: 'rags',
      type: 'robe',
      k: '襤褸',
      n: 'Rags',
      f: 'Patched a hundred times.',
      pk: 'Each lost life adds 0.25 to your score multiplier',
      tr: 'One fewer starting life',
      d: 'Fall 15 times.',
      ok: (s) => deathsTotal(s) >= 15,
      m: { scarScore: 0.25, lives: -1 },
    },
    {
      id: 'kabuki',
      type: 'robe',
      k: '歌舞伎',
      n: 'Kabuki lion',
      f: 'The white mane sways before the dance begins.',
      pk: 'Every 10-cut combo pays a growing bonus',
      tr: 'Enemies strike 6% faster',
      d: 'Reach a 70 combo.',
      ok: (s) => s.bestCombo >= 70,
      m: { comboBonus: 500, atk: 0.94 },
    },
    {
      id: 'scarecrow',
      type: 'robe',
      hidden: 1,
      k: '案山子',
      n: 'Scarecrow',
      f: 'Straw where the man should be.',
      pk: 'Enemies strike 15% slower',
      tr: 'Score ×0.6',
      hint: 'Crows scatter at the sound of clapping. Twenty claps on the title screen.',
      ok: (s) => s.scarecrow >= 1,
      m: { atk: 1.15, score: 0.6 },
    },
    {
      id: 'tanuki',
      type: 'robe',
      hidden: 1,
      k: '狸',
      n: 'Tanuki',
      f: "A trickster's costume.",
      pk: 'Feints 20 percentage points less likely; feints cannot cost a life',
      tr: 'Score ×0.75',
      hint: 'The trickster admires anyone who falls for a trick. Again, and again.',
      ok: (s) => s.feinted >= 3,
      m: { feint: -0.2, feintSafe: 1, score: 0.75 },
    },
    {
      id: 'nocharm',
      type: 'charm',
      k: '無',
      n: 'No charm',
      f: 'Travelling light.',
      ok: () => true,
    },
    {
      id: 'hisshou',
      type: 'charm',
      k: '必勝',
      n: 'Hisshō',
      f: 'Certain victory.',
      pk: 'Duel openings 10% longer',
      d: 'Win 3 duels.',
      ok: (s) => s.duels >= 3,
      m: { stag: 1.1 },
    },
    {
      id: 'kaiun',
      type: 'charm',
      k: '開運',
      n: 'Kaiun',
      f: 'Good fortune opens the way.',
      pk: 'Rare blessings appear more often',
      d: 'Take a cursed blessing.',
      ok: (s) => s.curses >= 1,
      m: { rare: 0.15 },
    },
    {
      id: 'yakuyoke',
      type: 'charm',
      k: '厄除',
      n: 'Yakuyoke',
      f: 'Wards off bad luck.',
      pk: 'Weather hazards 25% weaker',
      d: 'Reach the rain.',
      ok: (s) => s.furthestStage >= 3,
      m: { hazard: 0.75 },
    },
    {
      id: 'enmei',
      type: 'charm',
      k: '延命',
      n: 'Enmei',
      f: 'For a long life.',
      pk: 'Regain a life every 6 waves',
      d: 'Reach wave 9 without losing a life.',
      ok: (s) => s.flawless >= 1,
      m: { regen: 6 },
    },
    {
      id: 'shobai',
      type: 'charm',
      k: '商売',
      n: 'Shōbai',
      f: 'Prosperity in trade.',
      pk: 'Score ×1.1',
      d: 'Score 10,000 in one run.',
      ok: (s) => s.bestScore >= 10000,
      m: { score: 1.1 },
    },
    {
      id: 'kotsu',
      type: 'charm',
      k: '交通',
      n: 'Kōtsū anzen',
      f: 'Safe travels on the road.',
      pk: 'Standoff window 15% longer',
      d: 'Win a standoff.',
      ok: (s) => s.standoffs >= 1,
      m: { soWin: 1.15 },
    },
    {
      id: 'gakugyo',
      type: 'charm',
      k: '学業',
      n: 'Gakugyō',
      f: 'For diligent students.',
      pk: 'Perfect arc 10% larger',
      d: 'Land 10 perfect cuts.',
      ok: (s) => s.perfects >= 10,
      m: { pz: -0.02 },
    },
    {
      id: 'suzu',
      type: 'charm',
      k: '鈴',
      n: 'Suzu bell',
      f: 'A tiny bell on a red cord.',
      pk: 'A bell rings just before a feint turns',
      d: 'Cut down 50 feinting enemies.',
      ok: (s) => s.feintKills >= 50,
      m: { suzu: 1 },
    },
    {
      id: 'maneki',
      type: 'charm',
      k: '招猫',
      n: 'Maneki-neko',
      f: 'A beckoning cat.',
      pk: 'Every 7th kill drops a gold coin worth 500',
      d: 'Score 15,000 in one run.',
      ok: (s) => s.bestScore >= 15000,
      m: { maneki: 1 },
    },
    {
      id: 'daruma',
      type: 'charm',
      k: '達磨',
      n: 'Daruma',
      f: 'Seven times down, eight times up.',
      pk: 'Once per run, when you fall, rise again at the start of that wave',
      d: 'Fall 7 times.',
      ok: (s) => deathsTotal(s) >= 7,
      m: { daruma: 1 },
    },
    {
      id: 'kitsunebi',
      type: 'charm',
      k: '狐火',
      n: 'Kitsunebi',
      f: 'A little fox-fire follows you.',
      pk: 'Once per wave, fox-fire cuts down an attacker you were too slow for',
      d: 'Unlock the Kitsune mask.',
      ok: () => getUnlocks().has('kitsune'),
      m: { foxfire: 1 },
    },
    {
      id: 'furin',
      type: 'charm',
      k: '風鈴',
      n: 'Fūrin',
      f: 'A glass wind chime.',
      pk: 'Every 10-cut combo slows time for 2 seconds',
      d: 'Reach a 30 combo.',
      ok: (s) => s.bestCombo >= 30,
      m: { furin: 1 },
    },
    {
      id: 'ofuda',
      type: 'charm',
      k: '御札',
      n: 'Ofuda',
      f: 'A paper ward against deceit.',
      pk: 'A talisman marks every boss feint',
      d: 'Win 6 duels.',
      ok: (s) => s.duels >= 6,
      m: { ofuda: 1 },
    },
    {
      id: 'kinun',
      type: 'charm',
      k: '金運',
      n: "Kin'un",
      f: 'Luck with money.',
      pk: 'Wave-clear bonus doubled',
      d: 'Play 15 runs.',
      ok: (s) => s.runs >= 15,
      m: { waveBonus: 2 },
    },
    {
      id: 'kachi',
      type: 'charm',
      k: '勝守',
      n: 'Kachi-mamori',
      f: 'Carried for victory.',
      pk: 'Bosses have 1 less health',
      d: 'Win 3 duels without a failed opening.',
      ok: (s) => s.cleanDuels >= 3,
      m: { bossHp: -1 },
    },
    {
      id: 'shingan',
      type: 'charm',
      k: '心願',
      n: 'Shingan',
      f: 'A heartfelt wish.',
      pk: 'Combo multiplier caps at ×4.5',
      d: 'Reach an 80 endless combo.',
      ok: (s) => s.bestZen >= 80,
      m: { comboCap: 4.5 },
    },
    {
      id: 'ryoen',
      type: 'charm',
      k: '良縁',
      n: 'Ryōen',
      f: 'For good connections.',
      pk: '15% more breathing room between attackers',
      d: 'Accept 8 shrine blessings.',
      ok: (s) => s.shrines >= 8,
      m: { gap: 1.15 },
    },
    {
      id: 'kagami',
      type: 'charm',
      hidden: 1,
      k: '鏡',
      n: 'Kagami',
      f: 'A bronze mirror.',
      pk: 'Once per wave, a wrong cut is reflected into the right one',
      hint: 'Face the Mirror without a single flaw.',
      ok: (s) => s.mirrorClean >= 1,
      m: { kagami: 1 },
    },
    {
      id: 'omikuji',
      type: 'charm',
      hidden: 1,
      k: '御籤',
      n: 'Omikuji',
      f: 'A fortune slip, drawn before each run.',
      pk: 'Each run draws a random fortune, from great blessing to curse',
      hint: 'The shrine keeper answers those who knock. Three times.',
      ok: (s) => s.omikuji >= 1,
      m: {},
    },
    { id: 'nocrest', type: 'crest', k: '無', n: 'No crest', f: 'A plain back.', ok: () => true },
    {
      id: 'tomoe',
      type: 'crest',
      k: '巴',
      n: 'Mitsudomoe',
      f: 'Three swirling commas.',
      d: 'Play 3 runs.',
      ok: (s) => s.runs >= 3,
    },
    {
      id: 'kikyo',
      type: 'crest',
      k: '桔梗',
      n: 'Kikyō',
      f: 'The bellflower.',
      d: 'Win 2 duels.',
      ok: (s) => s.duels >= 2,
    },
    {
      id: 'juji',
      type: 'crest',
      k: '十字',
      n: 'Maru ni jūji',
      f: 'A cross in a ring.',
      d: 'Reach wave 8.',
      ok: (s) => s.bestWave >= 8,
    },
    {
      id: 'aoi',
      type: 'crest',
      k: '葵',
      n: 'Aoi',
      f: 'Three hollyhock leaves.',
      d: 'Accept 3 shrine blessings.',
      ok: (s) => s.shrines >= 3,
    },
    {
      id: 'fuji',
      type: 'crest',
      k: '藤',
      n: 'Sagari-fuji',
      f: 'Hanging wisteria.',
      d: 'Reach the cherry blossoms.',
      ok: (s) => s.furthestStage >= 2,
    },
    {
      id: 'tsuru',
      type: 'crest',
      k: '鶴',
      n: 'Tsuru-maru',
      f: 'A crane in a circle.',
      d: 'Reach a 50 endless combo.',
      ok: (s) => s.bestZen >= 50,
    },
    {
      id: 'rokumon',
      type: 'crest',
      k: '六文銭',
      n: 'Rokumonsen',
      f: 'Six coins for the river of the dead.',
      d: 'Fall 10 times.',
      ok: (s) => deathsTotal(s) >= 10,
    },
    { id: 'nopet', type: 'pet', k: '無', n: 'Alone', f: 'Just you and the wind.', ok: () => true },
    {
      id: 'crow',
      type: 'pet',
      k: '烏',
      n: 'Crow',
      f: 'Rides your shoulder. Flaps at every perfect cut.',
      d: 'Cut down 500 foes.',
      ok: (s) => s.kills >= 500,
    },
    {
      id: 'shiba',
      type: 'pet',
      k: '犬',
      n: 'Shiba',
      f: 'Sits in the grass. Barks when a feint turns.',
      d: 'Play 10 runs.',
      ok: (s) => s.runs >= 10,
    },
    {
      id: 'cat',
      type: 'pet',
      k: '猫',
      n: 'Cat',
      f: 'Watches from the rock. Judges you.',
      d: 'Spend 30 minutes on the field.',
      ok: (s) => s.time >= 1800,
    },
    { id: 'ink', type: 'fx', k: '墨', n: 'Ink', f: 'Black ink spray.', ok: () => true },
    {
      id: 'petals',
      type: 'fx',
      k: '花',
      n: 'Petals',
      f: 'A burst of blossom.',
      d: 'Cut down 300 foes.',
      ok: (s) => s.kills >= 300,
    },
    {
      id: 'bolt',
      type: 'fx',
      k: '雷',
      n: 'Lightning',
      f: 'The sky answers your cut.',
      d: 'Reach the stormy shore.',
      ok: (s) => s.furthestStage >= 7,
    },
    {
      id: 'embers',
      type: 'fx',
      k: '火',
      n: 'Embers',
      f: 'Sparks rise from the wound.',
      d: 'Reach the burning temple.',
      ok: (s) => s.furthestStage >= 6,
    },
    {
      id: 'crows',
      type: 'fx',
      k: '烏',
      n: 'Crows',
      f: 'They were waiting.',
      d: 'Fall 25 times.',
      ok: (s) => deathsTotal(s) >= 25,
    },
    {
      id: 'brush',
      type: 'fx',
      k: '斬',
      n: 'Calligraphy',
      f: 'Each cut signs its name.',
      d: 'Take 5 cursed blessings.',
      ok: (s) => s.curses >= 5,
    },
    {
      id: 'flies',
      type: 'fx',
      k: '蛍',
      n: 'Fireflies',
      f: 'Soft lights rise from the fallen.',
      d: 'Reach the moonlit night.',
      ok: (s) => s.furthestStage >= 8,
    },
    {
      id: 'shatter',
      type: 'fx',
      k: '砕',
      n: 'Shatter',
      f: 'They break like glass.',
      d: 'Win 3 duels in Ronin mode.',
      ok: (s) => s.roninDuels >= 3,
    },
    {
      id: 'crescent',
      type: 'fx',
      k: '月',
      n: 'Crescent',
      f: 'A silver crescent follows the cut.',
      d: 'Win 3 duels in one boss rush.',
      ok: (s) => s.rushBest >= 3,
    },
    {
      id: 'spirit',
      type: 'fx',
      k: '魂',
      n: 'Hitodama',
      f: 'A soul-flame drifts away.',
      d: 'Win 6 duels in one boss rush.',
      ok: (s) => s.rushBest >= 6,
    },
    {
      id: 'kintsugi',
      type: 'fx',
      k: '金継',
      n: 'Kintsugi',
      f: 'The wound mends in gold.',
      d: 'Win 9 duels in one boss rush.',
      ok: (s) => s.rushBest >= 9,
    },
    {
      id: 'wave',
      type: 'fx',
      k: '波',
      n: 'Great wave',
      f: 'A wave curls over the fallen.',
      d: 'Win 12 duels in one boss rush.',
      ok: (s) => s.rushBest >= 12,
    },
    {
      id: 'koi',
      type: 'fx',
      k: '鯉',
      n: 'Koi',
      f: 'Two koi leap from the cut.',
      d: 'Win a boss rush duel in blade-only mode.',
      ok: (s) => s.rushBlade >= 1,
    },
    {
      id: 'lanterns',
      type: 'fx',
      k: '灯籠',
      n: 'Lanterns',
      f: 'Paper lanterns rise into the dark.',
      d: 'Play 5 boss rush runs.',
      ok: (s) => s.rushRuns >= 5,
    },
    {
      id: 'maple',
      type: 'fx',
      k: '紅葉',
      n: 'Momiji',
      f: 'A burst of red maple leaves.',
      d: 'Accept 15 shrine blessings.',
      ok: (s) => s.shrines >= 15,
    },
    {
      id: 'cranes',
      type: 'fx',
      k: '鶴',
      n: 'Paper cranes',
      f: 'Folded cranes take flight.',
      d: 'Land 300 perfect cuts.',
      ok: (s) => s.perfects >= 300,
    },
    {
      id: 'poof',
      type: 'fx',
      k: '煙',
      n: 'Vanish',
      f: 'Gone in a puff of smoke.',
      d: 'Unlock the Shinobi outfit.',
      ok: () => getUnlocks().has('shinobi'),
    },
    {
      id: 'fireworks',
      type: 'fx',
      hidden: 1,
      k: '花火',
      n: 'Hanabi',
      f: 'Fireworks for every fallen foe.',
      hint: 'The sky celebrates at midnight.',
      ok: (s) => s.midnight >= 1,
    },
    {
      id: 'confetti',
      type: 'fx',
      hidden: 1,
      k: '紙吹雪',
      n: 'Confetti',
      f: 'A party for every cut.',
      hint: 'Even a fallen samurai deserves applause.',
      ok: (s) => s.applause >= 1,
    },
    {
      id: 'duck',
      type: 'fx',
      hidden: 1,
      k: '家鴨',
      n: 'Rubber duck',
      f: 'Squeak.',
      hint: 'Some warriors just cannot sit still.',
      ok: (s) => s.fidget >= 1,
    },
    {
      id: 'mono',
      type: 'film',
      k: '白黒',
      n: 'Monochrome',
      f: 'The original print.',
      ok: () => true,
    },
    {
      id: 'sepia',
      type: 'film',
      k: '褐',
      n: 'Sepia',
      f: 'An old studio print.',
      d: 'Play 5 runs.',
      ok: (s) => s.runs >= 5,
    },
    {
      id: 'silver',
      type: 'film',
      k: '銀',
      n: 'Silver',
      f: 'Cold blue-grey stock.',
      d: 'Reach the snow.',
      ok: (s) => s.furthestStage >= 5,
    },
    {
      id: 'noir',
      type: 'film',
      k: '黒白',
      n: 'Noir',
      f: 'Crushed blacks, hard light.',
      d: 'Win 3 duels in blade-only mode.',
      ok: (s) => s.bladeDuels >= 3,
    },
    {
      id: 'koda',
      type: 'film',
      k: '色',
      n: 'Faded colour',
      f: 'Warm highlights, teal shadows.',
      d: 'Unlock 12 armory items.',
      ok: () => getUnlocks().size >= 12,
    },
    {
      id: 'cyan',
      type: 'film',
      k: '藍写',
      n: 'Cyanotype',
      f: 'A blueprint-blue print.',
      d: 'Land 150 perfect cuts.',
      ok: (s) => s.perfects >= 150,
    },
    {
      id: 'nitrate',
      type: 'film',
      k: '古',
      n: 'Nitrate',
      f: 'A reel that barely survived.',
      d: 'Play 25 runs.',
      ok: (s) => s.runs >= 25,
    },
    {
      id: 'ukiyo',
      type: 'film',
      k: '浮世',
      n: 'Ukiyo-e',
      f: 'Indigo skies, ochre earth, woodblock paper.',
      d: 'Win 8 duels.',
      ok: (s) => s.duels >= 8,
    },
    { id: 'verm', type: 'seal', k: '朱', n: 'Vermilion', f: 'The classic seal.', ok: () => true },
    {
      id: 'gold',
      type: 'seal',
      k: '金',
      n: 'Gold',
      f: "For a lord's letters.",
      d: 'Score 30,000 in one run.',
      ok: (s) => s.bestScore >= 30000,
    },
    {
      id: 'indigo',
      type: 'seal',
      k: '藍',
      n: 'Indigo',
      f: 'Deep aizome dye.',
      d: 'Reach wave 15.',
      ok: (s) => s.bestWave >= 15,
    },
    {
      id: 'jade',
      type: 'seal',
      k: '翠',
      n: 'Jade',
      f: 'Cool green stone.',
      d: 'Win 3 standoffs.',
      ok: (s) => s.standoffs >= 3,
    },
    {
      id: 'sumiseal',
      type: 'seal',
      k: '墨',
      n: 'Ink',
      f: 'Black seal, pale arc.',
      d: 'Unlock every blade.',
      ok: () =>
        ['kuro', 'beni', 'tsuki', 'oboro', 'mura', 'raijin', 'sakura', 'kage', 'bokken'].every(
          (i) => getUnlocks().has(i),
        ),
    },
  ];
}
