/** Authoring identifiers and logical scene dependencies, independent of page layout. */
export const SCENERY_SOURCES = [
  'bamboo-atlas',
  'rocks-atlas',
  'pine-atlas',
  'mountain-atlas',
  'field-banks-atlas',
  'shrubs-atlas',
  'field-rocks-atlas',
  'grass-edges-atlas',
  'meadow-patches-atlas',
  'fog-wisps-atlas',
  'foreground-boulders-atlas',
  'cherry-trees-atlas',
  'petal-ground-atlas',
  'reeds-atlas',
  'snow-pines-atlas',
  'snow-boulders-atlas',
  'snow-rocks-atlas',
  'temple-posts-atlas',
  'temple-walls-atlas',
  'temple-roofs-atlas',
  'temple-steps-atlas',
  'sea-stacks-atlas',
  'foam-strips-atlas',
  'fallen-bamboo-atlas',
  'snow-peak',
  'demon-landmarks-atlas',
  'demon-terrain-atlas',
] as const;
export const SCENE_ASSETS = [
  [2, 3, 4, 5, 6, 7, 8, 9, 10],
  [2, 3, 4, 5, 6],
  [3, 4, 5, 6, 11, 12],
  [2, 3, 4, 5, 6, 7, 13],
  [0, 3, 4, 6, 23],
  [3, 14, 15, 16, 24],
  [2, 3, 6, 17, 18, 19, 20],
  [2, 3, 4, 6, 10, 21, 22],
  [2, 3, 6, 9, 17, 20],
] as const;
