// Generated by scripts/pbr/update-runtime-catalog.mjs. Do not edit by hand.
import type { PbrAtlasSources } from './pbr-atlas.ts';
interface AssetMaterialPack {
  sourcePath: string;
  source: string;
  dimensions: readonly [number, number];
  maps: PbrAtlasSources;
}
export const assetMaterialCatalog: readonly AssetMaterialPack[] = [
  {
    sourcePath: 'src/rendering/environment/assets/bamboo-atlas.png',
    source: new URL('./environment/assets/bamboo-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/bamboo-atlas/bamboo-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/bamboo-atlas/bamboo-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/bamboo-atlas/bamboo-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/bamboo-atlas/bamboo-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/bamboo-landmarks-atlas.png',
    source: new URL('./environment/assets/bamboo-landmarks-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/bamboo-landmarks-atlas/bamboo-landmarks-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/bamboo-landmarks-atlas/bamboo-landmarks-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/bamboo-landmarks-atlas/bamboo-landmarks-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/bamboo-landmarks-atlas/bamboo-landmarks-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/cherry-landmarks-atlas.png',
    source: new URL('./environment/assets/cherry-landmarks-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/cherry-landmarks-atlas/cherry-landmarks-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/cherry-landmarks-atlas/cherry-landmarks-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/cherry-landmarks-atlas/cherry-landmarks-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/cherry-landmarks-atlas/cherry-landmarks-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/cherry-trees-atlas.png',
    source: new URL('./environment/assets/cherry-trees-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/cherry-trees-atlas/cherry-trees-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/cherry-trees-atlas/cherry-trees-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/cherry-trees-atlas/cherry-trees-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/cherry-trees-atlas/cherry-trees-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/demon-landmarks-atlas.png',
    source: new URL('./environment/assets/demon-landmarks-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/demon-landmarks-atlas/demon-landmarks-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/demon-landmarks-atlas/demon-landmarks-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/demon-landmarks-atlas/demon-landmarks-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/demon-landmarks-atlas/demon-landmarks-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/demon-terrain-atlas.png',
    source: new URL('./environment/assets/demon-terrain-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/demon-terrain-atlas/demon-terrain-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/demon-terrain-atlas/demon-terrain-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/demon-terrain-atlas/demon-terrain-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/demon-terrain-atlas/demon-terrain-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/drift-debris-atlas.png',
    source: new URL('./environment/assets/drift-debris-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/drift-debris-atlas/drift-debris-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/drift-debris-atlas/drift-debris-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/drift-debris-atlas/drift-debris-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/drift-debris-atlas/drift-debris-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/drift-fire-atlas.png',
    source: new URL('./environment/assets/drift-fire-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/drift-fire-atlas/drift-fire-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/drift-fire-atlas/drift-fire-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/drift-fire-atlas/drift-fire-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/drift-fire-atlas/drift-fire-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/drift-leaves-atlas.png',
    source: new URL('./environment/assets/drift-leaves-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/drift-leaves-atlas/drift-leaves-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/drift-leaves-atlas/drift-leaves-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/drift-leaves-atlas/drift-leaves-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/drift-leaves-atlas/drift-leaves-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/drift-petals-atlas.png',
    source: new URL('./environment/assets/drift-petals-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/drift-petals-atlas/drift-petals-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/drift-petals-atlas/drift-petals-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/drift-petals-atlas/drift-petals-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/drift-petals-atlas/drift-petals-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/fallen-bamboo-atlas.png',
    source: new URL('./environment/assets/fallen-bamboo-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/fallen-bamboo-atlas/fallen-bamboo-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/fallen-bamboo-atlas/fallen-bamboo-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/fallen-bamboo-atlas/fallen-bamboo-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/fallen-bamboo-atlas/fallen-bamboo-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/field-banks-atlas.png',
    source: new URL('./environment/assets/field-banks-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/field-banks-atlas/field-banks-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/field-banks-atlas/field-banks-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/field-banks-atlas/field-banks-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/field-banks-atlas/field-banks-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/field-rocks-atlas.png',
    source: new URL('./environment/assets/field-rocks-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/field-rocks-atlas/field-rocks-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/field-rocks-atlas/field-rocks-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/field-rocks-atlas/field-rocks-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/field-rocks-atlas/field-rocks-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/foam-strips-atlas.png',
    source: new URL('./environment/assets/foam-strips-atlas.png', import.meta.url).href,
    dimensions: [1659, 948] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/foam-strips-atlas/foam-strips-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/foam-strips-atlas/foam-strips-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/foam-strips-atlas/foam-strips-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/foam-strips-atlas/foam-strips-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/fog-wisps-atlas.png',
    source: new URL('./environment/assets/fog-wisps-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/fog-wisps-atlas/fog-wisps-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/fog-wisps-atlas/fog-wisps-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/fog-wisps-atlas/fog-wisps-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/fog-wisps-atlas/fog-wisps-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/foreground-boulders-atlas.png',
    source: new URL('./environment/assets/foreground-boulders-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/foreground-boulders-atlas/foreground-boulders-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/foreground-boulders-atlas/foreground-boulders-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/foreground-boulders-atlas/foreground-boulders-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/foreground-boulders-atlas/foreground-boulders-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/grass-edges-atlas.png',
    source: new URL('./environment/assets/grass-edges-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/grass-edges-atlas/grass-edges-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/grass-edges-atlas/grass-edges-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/grass-edges-atlas/grass-edges-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/grass-edges-atlas/grass-edges-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/landmark-stones-atlas.png',
    source: new URL('./environment/assets/landmark-stones-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/landmark-stones-atlas/landmark-stones-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/landmark-stones-atlas/landmark-stones-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/landmark-stones-atlas/landmark-stones-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/landmark-stones-atlas/landmark-stones-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/meadow-patches-atlas.png',
    source: new URL('./environment/assets/meadow-patches-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/meadow-patches-atlas/meadow-patches-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/meadow-patches-atlas/meadow-patches-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/meadow-patches-atlas/meadow-patches-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/meadow-patches-atlas/meadow-patches-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/mountain-atlas.png',
    source: new URL('./environment/assets/mountain-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/mountain-atlas/mountain-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/mountain-atlas/mountain-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/mountain-atlas/mountain-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/mountain-atlas/mountain-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/petal-ground-atlas.png',
    source: new URL('./environment/assets/petal-ground-atlas.png', import.meta.url).href,
    dimensions: [1659, 948] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/petal-ground-atlas/petal-ground-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/petal-ground-atlas/petal-ground-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/petal-ground-atlas/petal-ground-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/petal-ground-atlas/petal-ground-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/pine-atlas.png',
    source: new URL('./environment/assets/pine-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/pine-atlas/pine-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL('./environment/assets/pbr/pine-atlas/pine-atlas_normal.png', import.meta.url)
        .href,
      surface: new URL(
        './environment/assets/pbr/pine-atlas/pine-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/pine-atlas/pine-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/reeds-atlas.png',
    source: new URL('./environment/assets/reeds-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/reeds-atlas/reeds-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/reeds-atlas/reeds-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/reeds-atlas/reeds-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/reeds-atlas/reeds-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/rocks-atlas.png',
    source: new URL('./environment/assets/rocks-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/rocks-atlas/rocks-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/rocks-atlas/rocks-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/rocks-atlas/rocks-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/rocks-atlas/rocks-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/sea-stacks-atlas.png',
    source: new URL('./environment/assets/sea-stacks-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/sea-stacks-atlas/sea-stacks-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/sea-stacks-atlas/sea-stacks-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/sea-stacks-atlas/sea-stacks-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/sea-stacks-atlas/sea-stacks-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/shrubs-atlas.png',
    source: new URL('./environment/assets/shrubs-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/shrubs-atlas/shrubs-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/shrubs-atlas/shrubs-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/shrubs-atlas/shrubs-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/shrubs-atlas/shrubs-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/snow-boulders-atlas.png',
    source: new URL('./environment/assets/snow-boulders-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/snow-boulders-atlas/snow-boulders-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/snow-boulders-atlas/snow-boulders-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/snow-boulders-atlas/snow-boulders-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/snow-boulders-atlas/snow-boulders-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/snow-peak.png',
    source: new URL('./environment/assets/snow-peak.png', import.meta.url).href,
    dimensions: [1881, 836] as const,
    maps: {
      diffuse: new URL('./environment/assets/pbr/snow-peak/snow-peak_diffuse.png', import.meta.url)
        .href,
      normal: new URL('./environment/assets/pbr/snow-peak/snow-peak_normal.png', import.meta.url)
        .href,
      surface: new URL('./environment/assets/pbr/snow-peak/snow-peak_surface.png', import.meta.url)
        .href,
      emissive: new URL(
        './environment/assets/pbr/snow-peak/snow-peak_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/snow-pines-atlas.png',
    source: new URL('./environment/assets/snow-pines-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/snow-pines-atlas/snow-pines-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/snow-pines-atlas/snow-pines-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/snow-pines-atlas/snow-pines-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/snow-pines-atlas/snow-pines-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/snow-rocks-atlas.png',
    source: new URL('./environment/assets/snow-rocks-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/snow-rocks-atlas/snow-rocks-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/snow-rocks-atlas/snow-rocks-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/snow-rocks-atlas/snow-rocks-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/snow-rocks-atlas/snow-rocks-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/snow-woodland-landmarks-atlas.png',
    source: new URL('./environment/assets/snow-woodland-landmarks-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/snow-woodland-landmarks-atlas/snow-woodland-landmarks-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/snow-woodland-landmarks-atlas/snow-woodland-landmarks-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/snow-woodland-landmarks-atlas/snow-woodland-landmarks-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/snow-woodland-landmarks-atlas/snow-woodland-landmarks-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/temple-posts-atlas.png',
    source: new URL('./environment/assets/temple-posts-atlas.png', import.meta.url).href,
    dimensions: [2172, 724] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/temple-posts-atlas/temple-posts-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/temple-posts-atlas/temple-posts-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/temple-posts-atlas/temple-posts-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/temple-posts-atlas/temple-posts-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/temple-roofs-atlas.png',
    source: new URL('./environment/assets/temple-roofs-atlas.png', import.meta.url).href,
    dimensions: [2172, 724] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/temple-roofs-atlas/temple-roofs-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/temple-roofs-atlas/temple-roofs-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/temple-roofs-atlas/temple-roofs-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/temple-roofs-atlas/temple-roofs-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/temple-steps-atlas.png',
    source: new URL('./environment/assets/temple-steps-atlas.png', import.meta.url).href,
    dimensions: [2172, 724] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/temple-steps-atlas/temple-steps-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/temple-steps-atlas/temple-steps-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/temple-steps-atlas/temple-steps-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/temple-steps-atlas/temple-steps-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/temple-walls-atlas.png',
    source: new URL('./environment/assets/temple-walls-atlas.png', import.meta.url).href,
    dimensions: [2172, 724] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/temple-walls-atlas/temple-walls-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/temple-walls-atlas/temple-walls-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/temple-walls-atlas/temple-walls-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/temple-walls-atlas/temple-walls-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/environment/assets/woodland-landmarks-atlas.png',
    source: new URL('./environment/assets/woodland-landmarks-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/woodland-landmarks-atlas/woodland-landmarks-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/woodland-landmarks-atlas/woodland-landmarks-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './environment/assets/pbr/woodland-landmarks-atlas/woodland-landmarks-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/woodland-landmarks-atlas/woodland-landmarks-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/figures/assets/armour-plates-atlas.png',
    source: new URL('./figures/assets/armour-plates-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './figures/assets/pbr/armour-plates-atlas/armour-plates-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './figures/assets/pbr/armour-plates-atlas/armour-plates-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './figures/assets/pbr/armour-plates-atlas/armour-plates-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './figures/assets/pbr/armour-plates-atlas/armour-plates-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/figures/assets/charm-atlas.png',
    source: new URL('./figures/assets/charm-atlas.png', import.meta.url).href,
    dimensions: [1536, 1024] as const,
    maps: {
      diffuse: new URL('./figures/assets/pbr/charm-atlas/charm-atlas_diffuse.png', import.meta.url)
        .href,
      normal: new URL('./figures/assets/pbr/charm-atlas/charm-atlas_normal.png', import.meta.url)
        .href,
      surface: new URL('./figures/assets/pbr/charm-atlas/charm-atlas_surface.png', import.meta.url)
        .href,
      emissive: new URL(
        './figures/assets/pbr/charm-atlas/charm-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/figures/assets/companion-atlas.png',
    source: new URL('./figures/assets/companion-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './figures/assets/pbr/companion-atlas/companion-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './figures/assets/pbr/companion-atlas/companion-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './figures/assets/pbr/companion-atlas/companion-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './figures/assets/pbr/companion-atlas/companion-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/figures/assets/companion-parts-atlas.png',
    source: new URL('./figures/assets/companion-parts-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './figures/assets/pbr/companion-parts-atlas/companion-parts-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './figures/assets/pbr/companion-parts-atlas/companion-parts-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './figures/assets/pbr/companion-parts-atlas/companion-parts-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './figures/assets/pbr/companion-parts-atlas/companion-parts-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/figures/assets/handle-guard-atlas.png',
    source: new URL('./figures/assets/handle-guard-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './figures/assets/pbr/handle-guard-atlas/handle-guard-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './figures/assets/pbr/handle-guard-atlas/handle-guard-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './figures/assets/pbr/handle-guard-atlas/handle-guard-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './figures/assets/pbr/handle-guard-atlas/handle-guard-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/figures/assets/katana.png',
    source: new URL('./figures/assets/katana.png', import.meta.url).href,
    dimensions: [2172, 724] as const,
    maps: {
      diffuse: new URL('./figures/assets/pbr/katana/katana_diffuse.png', import.meta.url).href,
      normal: new URL('./figures/assets/pbr/katana/katana_normal.png', import.meta.url).href,
      surface: new URL('./figures/assets/pbr/katana/katana_surface.png', import.meta.url).href,
      emissive: new URL('./figures/assets/pbr/katana/katana_emissive.png', import.meta.url).href,
    },
  },
  {
    sourcePath: 'src/rendering/figures/assets/mystic-rock.png',
    source: new URL('./figures/assets/mystic-rock.png', import.meta.url).href,
    dimensions: [1145, 1373] as const,
    maps: {
      diffuse: new URL('./figures/assets/pbr/mystic-rock/mystic-rock_diffuse.png', import.meta.url)
        .href,
      normal: new URL('./figures/assets/pbr/mystic-rock/mystic-rock_normal.png', import.meta.url)
        .href,
      surface: new URL('./figures/assets/pbr/mystic-rock/mystic-rock_surface.png', import.meta.url)
        .href,
      emissive: new URL(
        './figures/assets/pbr/mystic-rock/mystic-rock_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/figures/assets/outfit-cloth-atlas.png',
    source: new URL('./figures/assets/outfit-cloth-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './figures/assets/pbr/outfit-cloth-atlas/outfit-cloth-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './figures/assets/pbr/outfit-cloth-atlas/outfit-cloth-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './figures/assets/pbr/outfit-cloth-atlas/outfit-cloth-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './figures/assets/pbr/outfit-cloth-atlas/outfit-cloth-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/figures/assets/outfit-headwear-atlas.png',
    source: new URL('./figures/assets/outfit-headwear-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './figures/assets/pbr/outfit-headwear-atlas/outfit-headwear-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './figures/assets/pbr/outfit-headwear-atlas/outfit-headwear-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './figures/assets/pbr/outfit-headwear-atlas/outfit-headwear-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './figures/assets/pbr/outfit-headwear-atlas/outfit-headwear-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/figures/assets/player-mask-atlas.png',
    source: new URL('./figures/assets/player-mask-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './figures/assets/pbr/player-mask-atlas/player-mask-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './figures/assets/pbr/player-mask-atlas/player-mask-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './figures/assets/pbr/player-mask-atlas/player-mask-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './figures/assets/pbr/player-mask-atlas/player-mask-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/figures/assets/player-ronin-atlas.png',
    source: new URL('./figures/assets/player-ronin-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './figures/assets/pbr/player-ronin-atlas/player-ronin-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './figures/assets/pbr/player-ronin-atlas/player-ronin-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './figures/assets/pbr/player-ronin-atlas/player-ronin-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './figures/assets/pbr/player-ronin-atlas/player-ronin-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/figures/assets/player-special-headwear-atlas.png',
    source: new URL('./figures/assets/player-special-headwear-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './figures/assets/pbr/player-special-headwear-atlas/player-special-headwear-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './figures/assets/pbr/player-special-headwear-atlas/player-special-headwear-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './figures/assets/pbr/player-special-headwear-atlas/player-special-headwear-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './figures/assets/pbr/player-special-headwear-atlas/player-special-headwear-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/figures/assets/special-weapons-atlas.png',
    source: new URL('./figures/assets/special-weapons-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './figures/assets/pbr/special-weapons-atlas/special-weapons-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './figures/assets/pbr/special-weapons-atlas/special-weapons-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './figures/assets/pbr/special-weapons-atlas/special-weapons-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './figures/assets/pbr/special-weapons-atlas/special-weapons-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/armoury-room.png',
    source: new URL('./../ui/assets/armoury-room.png', import.meta.url).href,
    dimensions: [1536, 1024] as const,
    maps: {
      diffuse: new URL('./../ui/assets/pbr/armoury-room/armoury-room_diffuse.png', import.meta.url)
        .href,
      normal: new URL('./../ui/assets/pbr/armoury-room/armoury-room_normal.png', import.meta.url)
        .href,
      surface: new URL('./../ui/assets/pbr/armoury-room/armoury-room_surface.png', import.meta.url)
        .href,
      emissive: new URL(
        './../ui/assets/pbr/armoury-room/armoury-room_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/awakening-button-awakened.png',
    source: new URL('./../ui/assets/awakening-button-awakened.png', import.meta.url).href,
    dimensions: [256, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/awakening-button-awakened/awakening-button-awakened_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/awakening-button-awakened/awakening-button-awakened_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './../ui/assets/pbr/awakening-button-awakened/awakening-button-awakened_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/awakening-button-awakened/awakening-button-awakened_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/awakening-button-normal.png',
    source: new URL('./../ui/assets/awakening-button-normal.png', import.meta.url).href,
    dimensions: [256, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/awakening-button-normal/awakening-button-normal_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/awakening-button-normal/awakening-button-normal_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './../ui/assets/pbr/awakening-button-normal/awakening-button-normal_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/awakening-button-normal/awakening-button-normal_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/awakening-button-third.png',
    source: new URL('./../ui/assets/awakening-button-third.png', import.meta.url).href,
    dimensions: [256, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/awakening-button-third/awakening-button-third_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/awakening-button-third/awakening-button-third_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './../ui/assets/pbr/awakening-button-third/awakening-button-third_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/awakening-button-third/awakening-button-third_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/awakening-buttons-atlas.png',
    source: new URL('./../ui/assets/awakening-buttons-atlas.png', import.meta.url).href,
    dimensions: [768, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/awakening-buttons-atlas/awakening-buttons-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/awakening-buttons-atlas/awakening-buttons-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './../ui/assets/pbr/awakening-buttons-atlas/awakening-buttons-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/awakening-buttons-atlas/awakening-buttons-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/button-atlas.png',
    source: new URL('./../ui/assets/button-atlas.png', import.meta.url).href,
    dimensions: [256, 128] as const,
    maps: {
      diffuse: new URL('./../ui/assets/pbr/button-atlas/button-atlas_diffuse.png', import.meta.url)
        .href,
      normal: new URL('./../ui/assets/pbr/button-atlas/button-atlas_normal.png', import.meta.url)
        .href,
      surface: new URL('./../ui/assets/pbr/button-atlas/button-atlas_surface.png', import.meta.url)
        .href,
      emissive: new URL(
        './../ui/assets/pbr/button-atlas/button-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/button-highlighted.png',
    source: new URL('./../ui/assets/button-highlighted.png', import.meta.url).href,
    dimensions: [128, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/button-highlighted/button-highlighted_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/button-highlighted/button-highlighted_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './../ui/assets/pbr/button-highlighted/button-highlighted_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/button-highlighted/button-highlighted_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/button-normal.png',
    source: new URL('./../ui/assets/button-normal.png', import.meta.url).href,
    dimensions: [128, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/button-normal/button-normal_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL('./../ui/assets/pbr/button-normal/button-normal_normal.png', import.meta.url)
        .href,
      surface: new URL(
        './../ui/assets/pbr/button-normal/button-normal_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/button-normal/button-normal_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/demon-mirror-symbol.png',
    source: new URL('./../ui/assets/demon-mirror-symbol.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/demon-mirror-symbol/demon-mirror-symbol_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/demon-mirror-symbol/demon-mirror-symbol_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './../ui/assets/pbr/demon-mirror-symbol/demon-mirror-symbol_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/demon-mirror-symbol/demon-mirror-symbol_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/issen-logo.png',
    source: new URL('./../ui/assets/issen-logo.png', import.meta.url).href,
    dimensions: [600, 400] as const,
    maps: {
      diffuse: new URL('./../ui/assets/pbr/issen-logo/issen-logo_diffuse.png', import.meta.url)
        .href,
      normal: new URL('./../ui/assets/pbr/issen-logo/issen-logo_normal.png', import.meta.url).href,
      surface: new URL('./../ui/assets/pbr/issen-logo/issen-logo_surface.png', import.meta.url)
        .href,
      emissive: new URL('./../ui/assets/pbr/issen-logo/issen-logo_emissive.png', import.meta.url)
        .href,
    },
  },
  {
    sourcePath: 'src/ui/assets/panel-atlas.png',
    source: new URL('./../ui/assets/panel-atlas.png', import.meta.url).href,
    dimensions: [384, 192] as const,
    maps: {
      diffuse: new URL('./../ui/assets/pbr/panel-atlas/panel-atlas_diffuse.png', import.meta.url)
        .href,
      normal: new URL('./../ui/assets/pbr/panel-atlas/panel-atlas_normal.png', import.meta.url)
        .href,
      surface: new URL('./../ui/assets/pbr/panel-atlas/panel-atlas_surface.png', import.meta.url)
        .href,
      emissive: new URL('./../ui/assets/pbr/panel-atlas/panel-atlas_emissive.png', import.meta.url)
        .href,
    },
  },
  {
    sourcePath: 'src/ui/assets/panel-highlighted.png',
    source: new URL('./../ui/assets/panel-highlighted.png', import.meta.url).href,
    dimensions: [192, 192] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/panel-highlighted/panel-highlighted_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/panel-highlighted/panel-highlighted_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './../ui/assets/pbr/panel-highlighted/panel-highlighted_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/panel-highlighted/panel-highlighted_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/panel-normal.png',
    source: new URL('./../ui/assets/panel-normal.png', import.meta.url).href,
    dimensions: [192, 192] as const,
    maps: {
      diffuse: new URL('./../ui/assets/pbr/panel-normal/panel-normal_diffuse.png', import.meta.url)
        .href,
      normal: new URL('./../ui/assets/pbr/panel-normal/panel-normal_normal.png', import.meta.url)
        .href,
      surface: new URL('./../ui/assets/pbr/panel-normal/panel-normal_surface.png', import.meta.url)
        .href,
      emissive: new URL(
        './../ui/assets/pbr/panel-normal/panel-normal_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/temple-symbols-atlas.png',
    source: new URL('./../ui/assets/temple-symbols-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/temple-symbols-atlas/temple-symbols-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/temple-symbols-atlas/temple-symbols-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './../ui/assets/pbr/temple-symbols-atlas/temple-symbols-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/temple-symbols-atlas/temple-symbols-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/trial-symbols-atlas.png',
    source: new URL('./../ui/assets/trial-symbols-atlas.png', import.meta.url).href,
    dimensions: [1448, 1086] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/trial-symbols-atlas/trial-symbols-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/trial-symbols-atlas/trial-symbols-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './../ui/assets/pbr/trial-symbols-atlas/trial-symbols-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/trial-symbols-atlas/trial-symbols-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/ui-strokes-atlas.png',
    source: new URL('./../ui/assets/ui-strokes-atlas.png', import.meta.url).href,
    dimensions: [1536, 256] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/ui-strokes-atlas/ui-strokes-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/ui-strokes-atlas/ui-strokes-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './../ui/assets/pbr/ui-strokes-atlas/ui-strokes-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/ui-strokes-atlas/ui-strokes-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/world-ui-atlas.png',
    source: new URL('./../ui/assets/world-ui-atlas.png', import.meta.url).href,
    dimensions: [768, 640] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-atlas/world-ui-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-atlas/world-ui-atlas_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './../ui/assets/pbr/world-ui-atlas/world-ui-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-atlas/world-ui-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/world-ui-crest-aoi.png',
    source: new URL('./../ui/assets/world-ui-crest-aoi.png', import.meta.url).href,
    dimensions: [128, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-crest-aoi/world-ui-crest-aoi_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-crest-aoi/world-ui-crest-aoi_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './../ui/assets/pbr/world-ui-crest-aoi/world-ui-crest-aoi_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-crest-aoi/world-ui-crest-aoi_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/world-ui-crest-fuji.png',
    source: new URL('./../ui/assets/world-ui-crest-fuji.png', import.meta.url).href,
    dimensions: [128, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-crest-fuji/world-ui-crest-fuji_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-crest-fuji/world-ui-crest-fuji_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './../ui/assets/pbr/world-ui-crest-fuji/world-ui-crest-fuji_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-crest-fuji/world-ui-crest-fuji_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/world-ui-crest-juji.png',
    source: new URL('./../ui/assets/world-ui-crest-juji.png', import.meta.url).href,
    dimensions: [128, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-crest-juji/world-ui-crest-juji_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-crest-juji/world-ui-crest-juji_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './../ui/assets/pbr/world-ui-crest-juji/world-ui-crest-juji_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-crest-juji/world-ui-crest-juji_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/world-ui-crest-kikyo.png',
    source: new URL('./../ui/assets/world-ui-crest-kikyo.png', import.meta.url).href,
    dimensions: [128, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-crest-kikyo/world-ui-crest-kikyo_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-crest-kikyo/world-ui-crest-kikyo_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './../ui/assets/pbr/world-ui-crest-kikyo/world-ui-crest-kikyo_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-crest-kikyo/world-ui-crest-kikyo_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/world-ui-crest-rokumon.png',
    source: new URL('./../ui/assets/world-ui-crest-rokumon.png', import.meta.url).href,
    dimensions: [128, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-crest-rokumon/world-ui-crest-rokumon_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-crest-rokumon/world-ui-crest-rokumon_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './../ui/assets/pbr/world-ui-crest-rokumon/world-ui-crest-rokumon_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-crest-rokumon/world-ui-crest-rokumon_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/world-ui-crest-tomoe.png',
    source: new URL('./../ui/assets/world-ui-crest-tomoe.png', import.meta.url).href,
    dimensions: [128, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-crest-tomoe/world-ui-crest-tomoe_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-crest-tomoe/world-ui-crest-tomoe_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './../ui/assets/pbr/world-ui-crest-tomoe/world-ui-crest-tomoe_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-crest-tomoe/world-ui-crest-tomoe_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/world-ui-crest-tsuru.png',
    source: new URL('./../ui/assets/world-ui-crest-tsuru.png', import.meta.url).href,
    dimensions: [128, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-crest-tsuru/world-ui-crest-tsuru_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-crest-tsuru/world-ui-crest-tsuru_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './../ui/assets/pbr/world-ui-crest-tsuru/world-ui-crest-tsuru_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-crest-tsuru/world-ui-crest-tsuru_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/world-ui-material-metal.png',
    source: new URL('./../ui/assets/world-ui-material-metal.png', import.meta.url).href,
    dimensions: [192, 192] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-material-metal/world-ui-material-metal_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-material-metal/world-ui-material-metal_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './../ui/assets/pbr/world-ui-material-metal/world-ui-material-metal_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-material-metal/world-ui-material-metal_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/world-ui-material-paper.png',
    source: new URL('./../ui/assets/world-ui-material-paper.png', import.meta.url).href,
    dimensions: [192, 192] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-material-paper/world-ui-material-paper_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-material-paper/world-ui-material-paper_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './../ui/assets/pbr/world-ui-material-paper/world-ui-material-paper_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-material-paper/world-ui-material-paper_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/world-ui-material-silk.png',
    source: new URL('./../ui/assets/world-ui-material-silk.png', import.meta.url).href,
    dimensions: [192, 192] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-material-silk/world-ui-material-silk_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-material-silk/world-ui-material-silk_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './../ui/assets/pbr/world-ui-material-silk/world-ui-material-silk_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-material-silk/world-ui-material-silk_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/world-ui-material-stone.png',
    source: new URL('./../ui/assets/world-ui-material-stone.png', import.meta.url).href,
    dimensions: [192, 192] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-material-stone/world-ui-material-stone_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-material-stone/world-ui-material-stone_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './../ui/assets/pbr/world-ui-material-stone/world-ui-material-stone_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-material-stone/world-ui-material-stone_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/world-ui-material-wood.png',
    source: new URL('./../ui/assets/world-ui-material-wood.png', import.meta.url).href,
    dimensions: [192, 192] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-material-wood/world-ui-material-wood_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-material-wood/world-ui-material-wood_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './../ui/assets/pbr/world-ui-material-wood/world-ui-material-wood_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-material-wood/world-ui-material-wood_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/world-ui-scroll-paper.png',
    source: new URL('./../ui/assets/world-ui-scroll-paper.png', import.meta.url).href,
    dimensions: [192, 192] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-scroll-paper/world-ui-scroll-paper_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-scroll-paper/world-ui-scroll-paper_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './../ui/assets/pbr/world-ui-scroll-paper/world-ui-scroll-paper_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-scroll-paper/world-ui-scroll-paper_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/ui/assets/world-ui-scroll-rod.png',
    source: new URL('./../ui/assets/world-ui-scroll-rod.png', import.meta.url).href,
    dimensions: [192, 48] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-scroll-rod/world-ui-scroll-rod_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-scroll-rod/world-ui-scroll-rod_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './../ui/assets/pbr/world-ui-scroll-rod/world-ui-scroll-rod_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-scroll-rod/world-ui-scroll-rod_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/figures/assets/blade-profile-atlas.png',
    source: new URL('./figures/assets/blade-profile-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './figures/assets/blade-pbr/blade-profile-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL('./figures/assets/blade-pbr/blade-profile-atlas_normal.png', import.meta.url)
        .href,
      surface: new URL(
        './figures/assets/blade-pbr/blade-profile-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './figures/assets/blade-pbr/blade-profile-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/figures/assets/player-ronin-simple.png',
    source: new URL('./figures/assets/player-ronin-simple.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './figures/assets/player-pbr/player-ronin-simple_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL('./figures/assets/player-pbr/player-ronin-simple_normal.png', import.meta.url)
        .href,
      surface: new URL(
        './figures/assets/player-pbr/player-ronin-simple_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './figures/assets/player-pbr/player-ronin-simple_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/figures/assets/enemy-ronin-simple.png',
    source: new URL('./figures/assets/enemy-ronin-simple.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL('./figures/assets/enemy-pbr/enemy-ronin-simple_diffuse.png', import.meta.url)
        .href,
      normal: new URL('./figures/assets/enemy-pbr/enemy-ronin-simple_normal.png', import.meta.url)
        .href,
      surface: new URL('./figures/assets/enemy-pbr/enemy-ronin-simple_surface.png', import.meta.url)
        .href,
      emissive: new URL(
        './figures/assets/enemy-pbr/enemy-ronin-simple_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/figures/assets/enemy-clothing-variants.png',
    source: new URL('./figures/assets/enemy-clothing-variants.png', import.meta.url).href,
    dimensions: [1536, 1024] as const,
    maps: {
      diffuse: new URL(
        './figures/assets/enemy-pbr/enemy-clothing-variants_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './figures/assets/enemy-pbr/enemy-clothing-variants_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './figures/assets/enemy-pbr/enemy-clothing-variants_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './figures/assets/enemy-pbr/enemy-clothing-variants_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/figures/assets/enemy-headwear-atlas.png',
    source: new URL('./figures/assets/enemy-headwear-atlas.png', import.meta.url).href,
    dimensions: [1536, 1024] as const,
    maps: {
      diffuse: new URL(
        './figures/assets/enemy-pbr/enemy-headwear-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL('./figures/assets/enemy-pbr/enemy-headwear-atlas_normal.png', import.meta.url)
        .href,
      surface: new URL(
        './figures/assets/enemy-pbr/enemy-headwear-atlas_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './figures/assets/enemy-pbr/enemy-headwear-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    sourcePath: 'src/rendering/figures/assets/enemy-headwear-variants.png',
    source: new URL('./figures/assets/enemy-headwear-variants.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './figures/assets/enemy-pbr/enemy-headwear-variants_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './figures/assets/enemy-pbr/enemy-headwear-variants_normal.png',
        import.meta.url,
      ).href,
      surface: new URL(
        './figures/assets/enemy-pbr/enemy-headwear-variants_surface.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './figures/assets/enemy-pbr/enemy-headwear-variants_emissive.png',
        import.meta.url,
      ).href,
    },
  },
];
