// Generated by scripts/pbr/update-runtime-catalog.mjs. Do not edit by hand.
export const assetMaterialCatalog = [
  {
    source: new URL('./environment/assets/bamboo-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/bamboo-atlas/bamboo-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/bamboo-atlas/bamboo-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/bamboo-atlas/bamboo-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/bamboo-atlas/bamboo-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL('./environment/assets/pbr/bamboo-atlas/bamboo-atlas_ao.png', import.meta.url)
        .href,
      emissive: new URL(
        './environment/assets/pbr/bamboo-atlas/bamboo-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/bamboo-landmarks-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/bamboo-landmarks-atlas/bamboo-landmarks-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/bamboo-landmarks-atlas/bamboo-landmarks-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/bamboo-landmarks-atlas/bamboo-landmarks-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/bamboo-landmarks-atlas/bamboo-landmarks-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/bamboo-landmarks-atlas/bamboo-landmarks-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/bamboo-landmarks-atlas/bamboo-landmarks-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/cherry-landmarks-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/cherry-landmarks-atlas/cherry-landmarks-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/cherry-landmarks-atlas/cherry-landmarks-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/cherry-landmarks-atlas/cherry-landmarks-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/cherry-landmarks-atlas/cherry-landmarks-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/cherry-landmarks-atlas/cherry-landmarks-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/cherry-landmarks-atlas/cherry-landmarks-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/cherry-trees-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/cherry-trees-atlas/cherry-trees-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/cherry-trees-atlas/cherry-trees-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/cherry-trees-atlas/cherry-trees-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/cherry-trees-atlas/cherry-trees-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/cherry-trees-atlas/cherry-trees-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/cherry-trees-atlas/cherry-trees-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/demon-landmarks-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/demon-landmarks-atlas/demon-landmarks-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/demon-landmarks-atlas/demon-landmarks-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/demon-landmarks-atlas/demon-landmarks-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/demon-landmarks-atlas/demon-landmarks-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/demon-landmarks-atlas/demon-landmarks-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/demon-landmarks-atlas/demon-landmarks-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/demon-terrain-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/demon-terrain-atlas/demon-terrain-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/demon-terrain-atlas/demon-terrain-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/demon-terrain-atlas/demon-terrain-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/demon-terrain-atlas/demon-terrain-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/demon-terrain-atlas/demon-terrain-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/demon-terrain-atlas/demon-terrain-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/drift-debris-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/drift-debris-atlas/drift-debris-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/drift-debris-atlas/drift-debris-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/drift-debris-atlas/drift-debris-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/drift-debris-atlas/drift-debris-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/drift-debris-atlas/drift-debris-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/drift-debris-atlas/drift-debris-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/drift-fire-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/drift-fire-atlas/drift-fire-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/drift-fire-atlas/drift-fire-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/drift-fire-atlas/drift-fire-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/drift-fire-atlas/drift-fire-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/drift-fire-atlas/drift-fire-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/drift-fire-atlas/drift-fire-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/drift-leaves-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/drift-leaves-atlas/drift-leaves-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/drift-leaves-atlas/drift-leaves-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/drift-leaves-atlas/drift-leaves-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/drift-leaves-atlas/drift-leaves-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/drift-leaves-atlas/drift-leaves-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/drift-leaves-atlas/drift-leaves-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/drift-petals-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/drift-petals-atlas/drift-petals-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/drift-petals-atlas/drift-petals-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/drift-petals-atlas/drift-petals-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/drift-petals-atlas/drift-petals-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/drift-petals-atlas/drift-petals-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/drift-petals-atlas/drift-petals-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/fallen-bamboo-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/fallen-bamboo-atlas/fallen-bamboo-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/fallen-bamboo-atlas/fallen-bamboo-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/fallen-bamboo-atlas/fallen-bamboo-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/fallen-bamboo-atlas/fallen-bamboo-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/fallen-bamboo-atlas/fallen-bamboo-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/fallen-bamboo-atlas/fallen-bamboo-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/field-banks-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/field-banks-atlas/field-banks-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/field-banks-atlas/field-banks-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/field-banks-atlas/field-banks-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/field-banks-atlas/field-banks-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/field-banks-atlas/field-banks-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/field-banks-atlas/field-banks-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/field-rocks-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/field-rocks-atlas/field-rocks-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/field-rocks-atlas/field-rocks-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/field-rocks-atlas/field-rocks-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/field-rocks-atlas/field-rocks-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/field-rocks-atlas/field-rocks-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/field-rocks-atlas/field-rocks-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/foam-strips-atlas.png', import.meta.url).href,
    dimensions: [1659, 948] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/foam-strips-atlas/foam-strips-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/foam-strips-atlas/foam-strips-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/foam-strips-atlas/foam-strips-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/foam-strips-atlas/foam-strips-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/foam-strips-atlas/foam-strips-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/foam-strips-atlas/foam-strips-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/fog-wisps-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/fog-wisps-atlas/fog-wisps-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/fog-wisps-atlas/fog-wisps-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/fog-wisps-atlas/fog-wisps-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/fog-wisps-atlas/fog-wisps-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/fog-wisps-atlas/fog-wisps-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/fog-wisps-atlas/fog-wisps-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/foreground-boulders-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/foreground-boulders-atlas/foreground-boulders-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/foreground-boulders-atlas/foreground-boulders-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/foreground-boulders-atlas/foreground-boulders-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/foreground-boulders-atlas/foreground-boulders-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/foreground-boulders-atlas/foreground-boulders-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/foreground-boulders-atlas/foreground-boulders-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/grass-edges-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/grass-edges-atlas/grass-edges-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/grass-edges-atlas/grass-edges-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/grass-edges-atlas/grass-edges-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/grass-edges-atlas/grass-edges-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/grass-edges-atlas/grass-edges-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/grass-edges-atlas/grass-edges-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/landmark-stones-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/landmark-stones-atlas/landmark-stones-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/landmark-stones-atlas/landmark-stones-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/landmark-stones-atlas/landmark-stones-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/landmark-stones-atlas/landmark-stones-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/landmark-stones-atlas/landmark-stones-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/landmark-stones-atlas/landmark-stones-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/meadow-patches-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/meadow-patches-atlas/meadow-patches-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/meadow-patches-atlas/meadow-patches-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/meadow-patches-atlas/meadow-patches-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/meadow-patches-atlas/meadow-patches-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/meadow-patches-atlas/meadow-patches-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/meadow-patches-atlas/meadow-patches-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/mountain-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/mountain-atlas/mountain-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/mountain-atlas/mountain-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/mountain-atlas/mountain-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/mountain-atlas/mountain-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL('./environment/assets/pbr/mountain-atlas/mountain-atlas_ao.png', import.meta.url)
        .href,
      emissive: new URL(
        './environment/assets/pbr/mountain-atlas/mountain-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/petal-ground-atlas.png', import.meta.url).href,
    dimensions: [1659, 948] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/petal-ground-atlas/petal-ground-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/petal-ground-atlas/petal-ground-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/petal-ground-atlas/petal-ground-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/petal-ground-atlas/petal-ground-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/petal-ground-atlas/petal-ground-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/petal-ground-atlas/petal-ground-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/pine-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/pine-atlas/pine-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL('./environment/assets/pbr/pine-atlas/pine-atlas_normal.png', import.meta.url)
        .href,
      roughness: new URL(
        './environment/assets/pbr/pine-atlas/pine-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/pine-atlas/pine-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL('./environment/assets/pbr/pine-atlas/pine-atlas_ao.png', import.meta.url).href,
      emissive: new URL(
        './environment/assets/pbr/pine-atlas/pine-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/reeds-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/reeds-atlas/reeds-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/reeds-atlas/reeds-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/reeds-atlas/reeds-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/reeds-atlas/reeds-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL('./environment/assets/pbr/reeds-atlas/reeds-atlas_ao.png', import.meta.url).href,
      emissive: new URL(
        './environment/assets/pbr/reeds-atlas/reeds-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/rocks-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/rocks-atlas/rocks-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/rocks-atlas/rocks-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/rocks-atlas/rocks-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/rocks-atlas/rocks-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL('./environment/assets/pbr/rocks-atlas/rocks-atlas_ao.png', import.meta.url).href,
      emissive: new URL(
        './environment/assets/pbr/rocks-atlas/rocks-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/sea-stacks-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/sea-stacks-atlas/sea-stacks-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/sea-stacks-atlas/sea-stacks-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/sea-stacks-atlas/sea-stacks-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/sea-stacks-atlas/sea-stacks-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/sea-stacks-atlas/sea-stacks-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/sea-stacks-atlas/sea-stacks-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/shrubs-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/shrubs-atlas/shrubs-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/shrubs-atlas/shrubs-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/shrubs-atlas/shrubs-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/shrubs-atlas/shrubs-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL('./environment/assets/pbr/shrubs-atlas/shrubs-atlas_ao.png', import.meta.url)
        .href,
      emissive: new URL(
        './environment/assets/pbr/shrubs-atlas/shrubs-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/snow-boulders-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/snow-boulders-atlas/snow-boulders-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/snow-boulders-atlas/snow-boulders-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/snow-boulders-atlas/snow-boulders-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/snow-boulders-atlas/snow-boulders-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/snow-boulders-atlas/snow-boulders-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/snow-boulders-atlas/snow-boulders-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/snow-peak.png', import.meta.url).href,
    dimensions: [1881, 836] as const,
    maps: {
      diffuse: new URL('./environment/assets/pbr/snow-peak/snow-peak_diffuse.png', import.meta.url)
        .href,
      normal: new URL('./environment/assets/pbr/snow-peak/snow-peak_normal.png', import.meta.url)
        .href,
      roughness: new URL(
        './environment/assets/pbr/snow-peak/snow-peak_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/snow-peak/snow-peak_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL('./environment/assets/pbr/snow-peak/snow-peak_ao.png', import.meta.url).href,
      emissive: new URL(
        './environment/assets/pbr/snow-peak/snow-peak_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/snow-pines-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/snow-pines-atlas/snow-pines-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/snow-pines-atlas/snow-pines-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/snow-pines-atlas/snow-pines-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/snow-pines-atlas/snow-pines-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/snow-pines-atlas/snow-pines-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/snow-pines-atlas/snow-pines-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/snow-rocks-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/snow-rocks-atlas/snow-rocks-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/snow-rocks-atlas/snow-rocks-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/snow-rocks-atlas/snow-rocks-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/snow-rocks-atlas/snow-rocks-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/snow-rocks-atlas/snow-rocks-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/snow-rocks-atlas/snow-rocks-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/snow-woodland-landmarks-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/snow-woodland-landmarks-atlas/snow-woodland-landmarks-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/snow-woodland-landmarks-atlas/snow-woodland-landmarks-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/snow-woodland-landmarks-atlas/snow-woodland-landmarks-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/snow-woodland-landmarks-atlas/snow-woodland-landmarks-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/snow-woodland-landmarks-atlas/snow-woodland-landmarks-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/snow-woodland-landmarks-atlas/snow-woodland-landmarks-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/temple-posts-atlas.png', import.meta.url).href,
    dimensions: [2172, 724] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/temple-posts-atlas/temple-posts-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/temple-posts-atlas/temple-posts-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/temple-posts-atlas/temple-posts-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/temple-posts-atlas/temple-posts-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/temple-posts-atlas/temple-posts-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/temple-posts-atlas/temple-posts-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/temple-roofs-atlas.png', import.meta.url).href,
    dimensions: [2172, 724] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/temple-roofs-atlas/temple-roofs-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/temple-roofs-atlas/temple-roofs-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/temple-roofs-atlas/temple-roofs-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/temple-roofs-atlas/temple-roofs-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/temple-roofs-atlas/temple-roofs-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/temple-roofs-atlas/temple-roofs-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/temple-steps-atlas.png', import.meta.url).href,
    dimensions: [2172, 724] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/temple-steps-atlas/temple-steps-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/temple-steps-atlas/temple-steps-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/temple-steps-atlas/temple-steps-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/temple-steps-atlas/temple-steps-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/temple-steps-atlas/temple-steps-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/temple-steps-atlas/temple-steps-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/temple-walls-atlas.png', import.meta.url).href,
    dimensions: [2172, 724] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/temple-walls-atlas/temple-walls-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/temple-walls-atlas/temple-walls-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/temple-walls-atlas/temple-walls-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/temple-walls-atlas/temple-walls-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/temple-walls-atlas/temple-walls-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/temple-walls-atlas/temple-walls-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./environment/assets/woodland-landmarks-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './environment/assets/pbr/woodland-landmarks-atlas/woodland-landmarks-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './environment/assets/pbr/woodland-landmarks-atlas/woodland-landmarks-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './environment/assets/pbr/woodland-landmarks-atlas/woodland-landmarks-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './environment/assets/pbr/woodland-landmarks-atlas/woodland-landmarks-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './environment/assets/pbr/woodland-landmarks-atlas/woodland-landmarks-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './environment/assets/pbr/woodland-landmarks-atlas/woodland-landmarks-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./figures/assets/armour-plates-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './figures/assets/pbr/armour-plates-atlas/armour-plates-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './figures/assets/pbr/armour-plates-atlas/armour-plates-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './figures/assets/pbr/armour-plates-atlas/armour-plates-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './figures/assets/pbr/armour-plates-atlas/armour-plates-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './figures/assets/pbr/armour-plates-atlas/armour-plates-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './figures/assets/pbr/armour-plates-atlas/armour-plates-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./figures/assets/charm-atlas.png', import.meta.url).href,
    dimensions: [1536, 1024] as const,
    maps: {
      diffuse: new URL('./figures/assets/pbr/charm-atlas/charm-atlas_diffuse.png', import.meta.url)
        .href,
      normal: new URL('./figures/assets/pbr/charm-atlas/charm-atlas_normal.png', import.meta.url)
        .href,
      roughness: new URL(
        './figures/assets/pbr/charm-atlas/charm-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './figures/assets/pbr/charm-atlas/charm-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL('./figures/assets/pbr/charm-atlas/charm-atlas_ao.png', import.meta.url).href,
      emissive: new URL(
        './figures/assets/pbr/charm-atlas/charm-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./figures/assets/companion-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './figures/assets/pbr/companion-atlas/companion-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './figures/assets/pbr/companion-atlas/companion-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './figures/assets/pbr/companion-atlas/companion-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './figures/assets/pbr/companion-atlas/companion-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL('./figures/assets/pbr/companion-atlas/companion-atlas_ao.png', import.meta.url)
        .href,
      emissive: new URL(
        './figures/assets/pbr/companion-atlas/companion-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./figures/assets/companion-parts-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './figures/assets/pbr/companion-parts-atlas/companion-parts-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './figures/assets/pbr/companion-parts-atlas/companion-parts-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './figures/assets/pbr/companion-parts-atlas/companion-parts-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './figures/assets/pbr/companion-parts-atlas/companion-parts-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './figures/assets/pbr/companion-parts-atlas/companion-parts-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './figures/assets/pbr/companion-parts-atlas/companion-parts-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./figures/assets/handle-guard-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './figures/assets/pbr/handle-guard-atlas/handle-guard-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './figures/assets/pbr/handle-guard-atlas/handle-guard-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './figures/assets/pbr/handle-guard-atlas/handle-guard-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './figures/assets/pbr/handle-guard-atlas/handle-guard-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './figures/assets/pbr/handle-guard-atlas/handle-guard-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './figures/assets/pbr/handle-guard-atlas/handle-guard-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./figures/assets/katana.png', import.meta.url).href,
    dimensions: [2172, 724] as const,
    maps: {
      diffuse: new URL('./figures/assets/pbr/katana/katana_diffuse.png', import.meta.url).href,
      normal: new URL('./figures/assets/pbr/katana/katana_normal.png', import.meta.url).href,
      roughness: new URL('./figures/assets/pbr/katana/katana_roughness.png', import.meta.url).href,
      metallic: new URL('./figures/assets/pbr/katana/katana_metallic.png', import.meta.url).href,
      ao: new URL('./figures/assets/pbr/katana/katana_ao.png', import.meta.url).href,
      emissive: new URL('./figures/assets/pbr/katana/katana_emissive.png', import.meta.url).href,
    },
  },
  {
    source: new URL('./figures/assets/mystic-rock.png', import.meta.url).href,
    dimensions: [1145, 1373] as const,
    maps: {
      diffuse: new URL('./figures/assets/pbr/mystic-rock/mystic-rock_diffuse.png', import.meta.url)
        .href,
      normal: new URL('./figures/assets/pbr/mystic-rock/mystic-rock_normal.png', import.meta.url)
        .href,
      roughness: new URL(
        './figures/assets/pbr/mystic-rock/mystic-rock_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './figures/assets/pbr/mystic-rock/mystic-rock_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL('./figures/assets/pbr/mystic-rock/mystic-rock_ao.png', import.meta.url).href,
      emissive: new URL(
        './figures/assets/pbr/mystic-rock/mystic-rock_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./figures/assets/outfit-cloth-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './figures/assets/pbr/outfit-cloth-atlas/outfit-cloth-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './figures/assets/pbr/outfit-cloth-atlas/outfit-cloth-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './figures/assets/pbr/outfit-cloth-atlas/outfit-cloth-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './figures/assets/pbr/outfit-cloth-atlas/outfit-cloth-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './figures/assets/pbr/outfit-cloth-atlas/outfit-cloth-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './figures/assets/pbr/outfit-cloth-atlas/outfit-cloth-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./figures/assets/outfit-headwear-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './figures/assets/pbr/outfit-headwear-atlas/outfit-headwear-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './figures/assets/pbr/outfit-headwear-atlas/outfit-headwear-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './figures/assets/pbr/outfit-headwear-atlas/outfit-headwear-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './figures/assets/pbr/outfit-headwear-atlas/outfit-headwear-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './figures/assets/pbr/outfit-headwear-atlas/outfit-headwear-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './figures/assets/pbr/outfit-headwear-atlas/outfit-headwear-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./figures/assets/player-mask-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './figures/assets/pbr/player-mask-atlas/player-mask-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './figures/assets/pbr/player-mask-atlas/player-mask-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './figures/assets/pbr/player-mask-atlas/player-mask-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './figures/assets/pbr/player-mask-atlas/player-mask-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './figures/assets/pbr/player-mask-atlas/player-mask-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './figures/assets/pbr/player-mask-atlas/player-mask-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./figures/assets/player-ronin-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './figures/assets/pbr/player-ronin-atlas/player-ronin-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './figures/assets/pbr/player-ronin-atlas/player-ronin-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './figures/assets/pbr/player-ronin-atlas/player-ronin-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './figures/assets/pbr/player-ronin-atlas/player-ronin-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './figures/assets/pbr/player-ronin-atlas/player-ronin-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './figures/assets/pbr/player-ronin-atlas/player-ronin-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./figures/assets/player-special-headwear-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './figures/assets/pbr/player-special-headwear-atlas/player-special-headwear-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './figures/assets/pbr/player-special-headwear-atlas/player-special-headwear-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './figures/assets/pbr/player-special-headwear-atlas/player-special-headwear-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './figures/assets/pbr/player-special-headwear-atlas/player-special-headwear-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './figures/assets/pbr/player-special-headwear-atlas/player-special-headwear-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './figures/assets/pbr/player-special-headwear-atlas/player-special-headwear-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./figures/assets/special-weapons-atlas.png', import.meta.url).href,
    dimensions: [1774, 887] as const,
    maps: {
      diffuse: new URL(
        './figures/assets/pbr/special-weapons-atlas/special-weapons-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './figures/assets/pbr/special-weapons-atlas/special-weapons-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './figures/assets/pbr/special-weapons-atlas/special-weapons-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './figures/assets/pbr/special-weapons-atlas/special-weapons-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './figures/assets/pbr/special-weapons-atlas/special-weapons-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './figures/assets/pbr/special-weapons-atlas/special-weapons-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/armoury-room.png', import.meta.url).href,
    dimensions: [1536, 1024] as const,
    maps: {
      diffuse: new URL('./../ui/assets/pbr/armoury-room/armoury-room_diffuse.png', import.meta.url)
        .href,
      normal: new URL('./../ui/assets/pbr/armoury-room/armoury-room_normal.png', import.meta.url)
        .href,
      roughness: new URL(
        './../ui/assets/pbr/armoury-room/armoury-room_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/armoury-room/armoury-room_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL('./../ui/assets/pbr/armoury-room/armoury-room_ao.png', import.meta.url).href,
      emissive: new URL(
        './../ui/assets/pbr/armoury-room/armoury-room_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/awakening-button-awakened.png', import.meta.url).href,
    dimensions: [256, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/awakening-button-awakened/awakening-button-awakened_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/awakening-button-awakened/awakening-button-awakened_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './../ui/assets/pbr/awakening-button-awakened/awakening-button-awakened_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/awakening-button-awakened/awakening-button-awakened_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './../ui/assets/pbr/awakening-button-awakened/awakening-button-awakened_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/awakening-button-awakened/awakening-button-awakened_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/awakening-button-normal.png', import.meta.url).href,
    dimensions: [256, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/awakening-button-normal/awakening-button-normal_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/awakening-button-normal/awakening-button-normal_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './../ui/assets/pbr/awakening-button-normal/awakening-button-normal_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/awakening-button-normal/awakening-button-normal_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './../ui/assets/pbr/awakening-button-normal/awakening-button-normal_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/awakening-button-normal/awakening-button-normal_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/awakening-button-third.png', import.meta.url).href,
    dimensions: [256, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/awakening-button-third/awakening-button-third_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/awakening-button-third/awakening-button-third_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './../ui/assets/pbr/awakening-button-third/awakening-button-third_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/awakening-button-third/awakening-button-third_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './../ui/assets/pbr/awakening-button-third/awakening-button-third_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/awakening-button-third/awakening-button-third_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/awakening-buttons-atlas.png', import.meta.url).href,
    dimensions: [768, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/awakening-buttons-atlas/awakening-buttons-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/awakening-buttons-atlas/awakening-buttons-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './../ui/assets/pbr/awakening-buttons-atlas/awakening-buttons-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/awakening-buttons-atlas/awakening-buttons-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './../ui/assets/pbr/awakening-buttons-atlas/awakening-buttons-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/awakening-buttons-atlas/awakening-buttons-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/button-atlas.png', import.meta.url).href,
    dimensions: [256, 128] as const,
    maps: {
      diffuse: new URL('./../ui/assets/pbr/button-atlas/button-atlas_diffuse.png', import.meta.url)
        .href,
      normal: new URL('./../ui/assets/pbr/button-atlas/button-atlas_normal.png', import.meta.url)
        .href,
      roughness: new URL(
        './../ui/assets/pbr/button-atlas/button-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/button-atlas/button-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL('./../ui/assets/pbr/button-atlas/button-atlas_ao.png', import.meta.url).href,
      emissive: new URL(
        './../ui/assets/pbr/button-atlas/button-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/button-highlighted.png', import.meta.url).href,
    dimensions: [128, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/button-highlighted/button-highlighted_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/button-highlighted/button-highlighted_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './../ui/assets/pbr/button-highlighted/button-highlighted_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/button-highlighted/button-highlighted_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './../ui/assets/pbr/button-highlighted/button-highlighted_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/button-highlighted/button-highlighted_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/button-normal.png', import.meta.url).href,
    dimensions: [128, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/button-normal/button-normal_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL('./../ui/assets/pbr/button-normal/button-normal_normal.png', import.meta.url)
        .href,
      roughness: new URL(
        './../ui/assets/pbr/button-normal/button-normal_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/button-normal/button-normal_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL('./../ui/assets/pbr/button-normal/button-normal_ao.png', import.meta.url).href,
      emissive: new URL(
        './../ui/assets/pbr/button-normal/button-normal_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/demon-mirror-symbol.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/demon-mirror-symbol/demon-mirror-symbol_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/demon-mirror-symbol/demon-mirror-symbol_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './../ui/assets/pbr/demon-mirror-symbol/demon-mirror-symbol_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/demon-mirror-symbol/demon-mirror-symbol_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './../ui/assets/pbr/demon-mirror-symbol/demon-mirror-symbol_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/demon-mirror-symbol/demon-mirror-symbol_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/issen-logo.png', import.meta.url).href,
    dimensions: [600, 400] as const,
    maps: {
      diffuse: new URL('./../ui/assets/pbr/issen-logo/issen-logo_diffuse.png', import.meta.url)
        .href,
      normal: new URL('./../ui/assets/pbr/issen-logo/issen-logo_normal.png', import.meta.url).href,
      roughness: new URL('./../ui/assets/pbr/issen-logo/issen-logo_roughness.png', import.meta.url)
        .href,
      metallic: new URL('./../ui/assets/pbr/issen-logo/issen-logo_metallic.png', import.meta.url)
        .href,
      ao: new URL('./../ui/assets/pbr/issen-logo/issen-logo_ao.png', import.meta.url).href,
      emissive: new URL('./../ui/assets/pbr/issen-logo/issen-logo_emissive.png', import.meta.url)
        .href,
    },
  },
  {
    source: new URL('./../ui/assets/panel-atlas.png', import.meta.url).href,
    dimensions: [384, 192] as const,
    maps: {
      diffuse: new URL('./../ui/assets/pbr/panel-atlas/panel-atlas_diffuse.png', import.meta.url)
        .href,
      normal: new URL('./../ui/assets/pbr/panel-atlas/panel-atlas_normal.png', import.meta.url)
        .href,
      roughness: new URL(
        './../ui/assets/pbr/panel-atlas/panel-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL('./../ui/assets/pbr/panel-atlas/panel-atlas_metallic.png', import.meta.url)
        .href,
      ao: new URL('./../ui/assets/pbr/panel-atlas/panel-atlas_ao.png', import.meta.url).href,
      emissive: new URL('./../ui/assets/pbr/panel-atlas/panel-atlas_emissive.png', import.meta.url)
        .href,
    },
  },
  {
    source: new URL('./../ui/assets/panel-highlighted.png', import.meta.url).href,
    dimensions: [192, 192] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/panel-highlighted/panel-highlighted_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/panel-highlighted/panel-highlighted_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './../ui/assets/pbr/panel-highlighted/panel-highlighted_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/panel-highlighted/panel-highlighted_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL('./../ui/assets/pbr/panel-highlighted/panel-highlighted_ao.png', import.meta.url)
        .href,
      emissive: new URL(
        './../ui/assets/pbr/panel-highlighted/panel-highlighted_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/panel-normal.png', import.meta.url).href,
    dimensions: [192, 192] as const,
    maps: {
      diffuse: new URL('./../ui/assets/pbr/panel-normal/panel-normal_diffuse.png', import.meta.url)
        .href,
      normal: new URL('./../ui/assets/pbr/panel-normal/panel-normal_normal.png', import.meta.url)
        .href,
      roughness: new URL(
        './../ui/assets/pbr/panel-normal/panel-normal_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/panel-normal/panel-normal_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL('./../ui/assets/pbr/panel-normal/panel-normal_ao.png', import.meta.url).href,
      emissive: new URL(
        './../ui/assets/pbr/panel-normal/panel-normal_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/temple-symbols-atlas.png', import.meta.url).href,
    dimensions: [1254, 1254] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/temple-symbols-atlas/temple-symbols-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/temple-symbols-atlas/temple-symbols-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './../ui/assets/pbr/temple-symbols-atlas/temple-symbols-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/temple-symbols-atlas/temple-symbols-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './../ui/assets/pbr/temple-symbols-atlas/temple-symbols-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/temple-symbols-atlas/temple-symbols-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/trial-symbols-atlas.png', import.meta.url).href,
    dimensions: [1448, 1086] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/trial-symbols-atlas/trial-symbols-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/trial-symbols-atlas/trial-symbols-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './../ui/assets/pbr/trial-symbols-atlas/trial-symbols-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/trial-symbols-atlas/trial-symbols-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './../ui/assets/pbr/trial-symbols-atlas/trial-symbols-atlas_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/trial-symbols-atlas/trial-symbols-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/ui-strokes-atlas.png', import.meta.url).href,
    dimensions: [1536, 256] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/ui-strokes-atlas/ui-strokes-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/ui-strokes-atlas/ui-strokes-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './../ui/assets/pbr/ui-strokes-atlas/ui-strokes-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/ui-strokes-atlas/ui-strokes-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL('./../ui/assets/pbr/ui-strokes-atlas/ui-strokes-atlas_ao.png', import.meta.url)
        .href,
      emissive: new URL(
        './../ui/assets/pbr/ui-strokes-atlas/ui-strokes-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/world-ui-atlas.png', import.meta.url).href,
    dimensions: [768, 640] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-atlas/world-ui-atlas_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-atlas/world-ui-atlas_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './../ui/assets/pbr/world-ui-atlas/world-ui-atlas_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/world-ui-atlas/world-ui-atlas_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL('./../ui/assets/pbr/world-ui-atlas/world-ui-atlas_ao.png', import.meta.url).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-atlas/world-ui-atlas_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/world-ui-crest-aoi.png', import.meta.url).href,
    dimensions: [128, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-crest-aoi/world-ui-crest-aoi_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-crest-aoi/world-ui-crest-aoi_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './../ui/assets/pbr/world-ui-crest-aoi/world-ui-crest-aoi_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/world-ui-crest-aoi/world-ui-crest-aoi_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './../ui/assets/pbr/world-ui-crest-aoi/world-ui-crest-aoi_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-crest-aoi/world-ui-crest-aoi_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/world-ui-crest-fuji.png', import.meta.url).href,
    dimensions: [128, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-crest-fuji/world-ui-crest-fuji_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-crest-fuji/world-ui-crest-fuji_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './../ui/assets/pbr/world-ui-crest-fuji/world-ui-crest-fuji_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/world-ui-crest-fuji/world-ui-crest-fuji_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './../ui/assets/pbr/world-ui-crest-fuji/world-ui-crest-fuji_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-crest-fuji/world-ui-crest-fuji_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/world-ui-crest-juji.png', import.meta.url).href,
    dimensions: [128, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-crest-juji/world-ui-crest-juji_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-crest-juji/world-ui-crest-juji_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './../ui/assets/pbr/world-ui-crest-juji/world-ui-crest-juji_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/world-ui-crest-juji/world-ui-crest-juji_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './../ui/assets/pbr/world-ui-crest-juji/world-ui-crest-juji_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-crest-juji/world-ui-crest-juji_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/world-ui-crest-kikyo.png', import.meta.url).href,
    dimensions: [128, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-crest-kikyo/world-ui-crest-kikyo_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-crest-kikyo/world-ui-crest-kikyo_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './../ui/assets/pbr/world-ui-crest-kikyo/world-ui-crest-kikyo_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/world-ui-crest-kikyo/world-ui-crest-kikyo_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './../ui/assets/pbr/world-ui-crest-kikyo/world-ui-crest-kikyo_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-crest-kikyo/world-ui-crest-kikyo_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/world-ui-crest-rokumon.png', import.meta.url).href,
    dimensions: [128, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-crest-rokumon/world-ui-crest-rokumon_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-crest-rokumon/world-ui-crest-rokumon_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './../ui/assets/pbr/world-ui-crest-rokumon/world-ui-crest-rokumon_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/world-ui-crest-rokumon/world-ui-crest-rokumon_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './../ui/assets/pbr/world-ui-crest-rokumon/world-ui-crest-rokumon_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-crest-rokumon/world-ui-crest-rokumon_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/world-ui-crest-tomoe.png', import.meta.url).href,
    dimensions: [128, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-crest-tomoe/world-ui-crest-tomoe_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-crest-tomoe/world-ui-crest-tomoe_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './../ui/assets/pbr/world-ui-crest-tomoe/world-ui-crest-tomoe_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/world-ui-crest-tomoe/world-ui-crest-tomoe_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './../ui/assets/pbr/world-ui-crest-tomoe/world-ui-crest-tomoe_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-crest-tomoe/world-ui-crest-tomoe_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/world-ui-crest-tsuru.png', import.meta.url).href,
    dimensions: [128, 128] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-crest-tsuru/world-ui-crest-tsuru_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-crest-tsuru/world-ui-crest-tsuru_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './../ui/assets/pbr/world-ui-crest-tsuru/world-ui-crest-tsuru_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/world-ui-crest-tsuru/world-ui-crest-tsuru_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './../ui/assets/pbr/world-ui-crest-tsuru/world-ui-crest-tsuru_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-crest-tsuru/world-ui-crest-tsuru_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/world-ui-material-metal.png', import.meta.url).href,
    dimensions: [192, 192] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-material-metal/world-ui-material-metal_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-material-metal/world-ui-material-metal_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './../ui/assets/pbr/world-ui-material-metal/world-ui-material-metal_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/world-ui-material-metal/world-ui-material-metal_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './../ui/assets/pbr/world-ui-material-metal/world-ui-material-metal_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-material-metal/world-ui-material-metal_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/world-ui-material-paper.png', import.meta.url).href,
    dimensions: [192, 192] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-material-paper/world-ui-material-paper_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-material-paper/world-ui-material-paper_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './../ui/assets/pbr/world-ui-material-paper/world-ui-material-paper_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/world-ui-material-paper/world-ui-material-paper_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './../ui/assets/pbr/world-ui-material-paper/world-ui-material-paper_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-material-paper/world-ui-material-paper_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/world-ui-material-silk.png', import.meta.url).href,
    dimensions: [192, 192] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-material-silk/world-ui-material-silk_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-material-silk/world-ui-material-silk_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './../ui/assets/pbr/world-ui-material-silk/world-ui-material-silk_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/world-ui-material-silk/world-ui-material-silk_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './../ui/assets/pbr/world-ui-material-silk/world-ui-material-silk_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-material-silk/world-ui-material-silk_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/world-ui-material-stone.png', import.meta.url).href,
    dimensions: [192, 192] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-material-stone/world-ui-material-stone_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-material-stone/world-ui-material-stone_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './../ui/assets/pbr/world-ui-material-stone/world-ui-material-stone_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/world-ui-material-stone/world-ui-material-stone_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './../ui/assets/pbr/world-ui-material-stone/world-ui-material-stone_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-material-stone/world-ui-material-stone_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/world-ui-material-wood.png', import.meta.url).href,
    dimensions: [192, 192] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-material-wood/world-ui-material-wood_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-material-wood/world-ui-material-wood_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './../ui/assets/pbr/world-ui-material-wood/world-ui-material-wood_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/world-ui-material-wood/world-ui-material-wood_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './../ui/assets/pbr/world-ui-material-wood/world-ui-material-wood_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-material-wood/world-ui-material-wood_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/world-ui-scroll-paper.png', import.meta.url).href,
    dimensions: [192, 192] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-scroll-paper/world-ui-scroll-paper_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-scroll-paper/world-ui-scroll-paper_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './../ui/assets/pbr/world-ui-scroll-paper/world-ui-scroll-paper_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/world-ui-scroll-paper/world-ui-scroll-paper_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './../ui/assets/pbr/world-ui-scroll-paper/world-ui-scroll-paper_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-scroll-paper/world-ui-scroll-paper_emissive.png',
        import.meta.url,
      ).href,
    },
  },
  {
    source: new URL('./../ui/assets/world-ui-scroll-rod.png', import.meta.url).href,
    dimensions: [192, 48] as const,
    maps: {
      diffuse: new URL(
        './../ui/assets/pbr/world-ui-scroll-rod/world-ui-scroll-rod_diffuse.png',
        import.meta.url,
      ).href,
      normal: new URL(
        './../ui/assets/pbr/world-ui-scroll-rod/world-ui-scroll-rod_normal.png',
        import.meta.url,
      ).href,
      roughness: new URL(
        './../ui/assets/pbr/world-ui-scroll-rod/world-ui-scroll-rod_roughness.png',
        import.meta.url,
      ).href,
      metallic: new URL(
        './../ui/assets/pbr/world-ui-scroll-rod/world-ui-scroll-rod_metallic.png',
        import.meta.url,
      ).href,
      ao: new URL(
        './../ui/assets/pbr/world-ui-scroll-rod/world-ui-scroll-rod_ao.png',
        import.meta.url,
      ).href,
      emissive: new URL(
        './../ui/assets/pbr/world-ui-scroll-rod/world-ui-scroll-rod_emissive.png',
        import.meta.url,
      ).href,
    },
  },
] as const;
